"""
Prompt Generation for Sound Box
Generates thousands of targeted prompts for empty categories.
Each prompt is designed to match exactly one primary category.
"""

import random

# =============================================================================
# EMPTY MUSIC CATEGORIES - Need content generation
# =============================================================================

MUSIC_PROMPTS = {
    # === ERA-SPECIFIC ===
    '60s': [
        "1960s psychedelic rock with swirling organs and fuzzy guitars",
        "sixties british invasion pop song with jangly guitars",
        "1960s motown soul hit with brass section and backup singers",
        "60s surf rock instrumental with reverb-drenched guitars",
        "sixties folk protest song with acoustic guitar and harmonica",
        "1960s garage rock with raw distorted guitars and tambourine",
        "60s doo-wop ballad with harmonizing vocals",
        "sixties bossa nova jazz with gentle percussion",
        "1960s girl group pop with wall of sound production",
        "60s mod jazz with walking bass and brushed drums",
        "sixties acid rock with extended guitar solo",
        "1960s easy listening orchestral arrangement",
        "60s rockabilly revival with slap bass",
        "sixties rhythm and blues with organ",
        "1960s baroque pop with harpsichord",
        "60s flower power anthem with sitar",
        "sixties beat music with driving rhythm",
        "1960s west coast pop sunshine sound",
        "60s southern soul with horns",
        "sixties freakbeat with fuzz guitar",
    ],

    '70s': [
        "1970s disco hit with four on the floor beat and strings",
        "seventies progressive rock epic with synthesizer solo",
        "70s funk groove with slap bass and wah guitar",
        "1970s punk rock anthem fast and aggressive",
        "seventies soft rock ballad with acoustic guitar",
        "70s glam rock with stomping beat and handclaps",
        "1970s krautrock motorik rhythm with synths",
        "seventies reggae with offbeat guitar skank",
        "70s southern rock with twin guitar harmonies",
        "1970s jazz fusion with electric piano",
        "seventies arena rock power ballad",
        "70s new wave with angular guitars",
        "1970s country rock with pedal steel",
        "seventies soul with lush string arrangement",
        "70s hard rock with heavy riffs",
        "1970s electronic music pioneers style",
        "seventies blaxploitation soundtrack funk",
        "70s singer songwriter folk rock",
        "1970s proto-metal heavy and dark",
        "seventies yacht rock smooth production",
    ],

    '80s': [
        "1980s synth pop with arpeggiated synthesizers and gated drums",
        "eighties power ballad with soaring guitar solo",
        "80s new wave with chorus guitar and synth bass",
        "1980s hair metal anthem with shredding guitar",
        "eighties italo disco with pulsing bass and vocoder",
        "80s hip hop breakbeat with scratching",
        "1980s post-punk with dark bass and angular guitar",
        "eighties freestyle dance track with latin percussion",
        "80s synthwave with retro futuristic vibes",
        "1980s college rock with jangly guitars",
        "eighties electro funk with drum machines",
        "80s stadium rock with big chorus",
        "1980s goth rock with brooding atmosphere",
        "eighties pop rock radio hit",
        "80s industrial with mechanical rhythms",
        "1980s boogie funk with slap bass",
        "eighties eurodisco with catchy hooks",
        "80s thrash metal fast and aggressive",
        "1980s sophisti-pop with saxophone",
        "eighties art pop with experimental sounds",
    ],

    # === WORLD & ETHNIC ===
    'african': [
        "african highlife music with palm wine guitar and percussion",
        "afrobeat groove with driving polyrhythmic drums and horns",
        "west african kora music gentle and melodic",
        "african mbira music hypnotic kalimba patterns",
        "ethiopian jazz with unique scales and brass",
        "african soukous dance music with fast guitar",
        "nigerian juju music with talking drums",
        "south african township jive kwela style",
        "african desert blues with hypnotic guitar",
        "congolese rumba with flowing guitar lines",
        "african percussion ensemble djembe and dundun",
        "malian griot music traditional storytelling",
        "afro-cuban fusion with african roots",
        "african gospel choir harmonies",
        "senegalese mbalax dance rhythm",
        "african electronic fusion modern production",
        "traditional african lullaby gentle soothing",
        "african wedding celebration music joyful",
        "cape verdean morna melancholic beautiful",
        "african tribal ceremony drums intense",
    ],

    'celtic': [
        "celtic folk music with fiddle and tin whistle",
        "irish jig lively dance tune with bodhran",
        "scottish bagpipe march powerful and stirring",
        "celtic harp music gentle and ethereal",
        "irish rebel song with accordion and guitar",
        "celtic new age music mystical atmosphere",
        "scottish strathspey dance music",
        "irish sean-nos traditional singing style",
        "celtic rock fusion with electric instruments",
        "welsh choir harmonies powerful and moving",
        "irish pub session music lively and fun",
        "celtic lament slow and mournful",
        "scottish folk ballad storytelling",
        "irish reel fast tempo dance music",
        "celtic meditation music peaceful harps",
        "breton folk music from brittany",
        "celtic christmas carol traditional",
        "irish slip jig in 9/8 time",
        "scottish folk guitar fingerstyle",
        "celtic fusion world music blend",
    ],

    'latin': [
        "latin salsa music with congas and brass section",
        "cuban son traditional with tres guitar",
        "brazilian bossa nova smooth and intimate",
        "mexican mariachi with trumpets and violins",
        "argentine tango dramatic and passionate",
        "colombian cumbia tropical dance rhythm",
        "puerto rican reggaeton urban beat",
        "latin jazz piano montuno patterns",
        "spanish flamenco with passionate guitar",
        "cuban mambo big band arrangement",
        "brazilian samba percussion carnival",
        "latin pop ballad romantic",
        "peruvian huayno andean folk",
        "dominican merengue fast dance beat",
        "cuban cha-cha-cha dance music",
        "latin rock fusion with guitar",
        "bachata romantic dominican style",
        "latin electronic dance modern",
        "bolero slow romantic ballad",
        "latin funk with horn section",
    ],

    'middle_eastern': [
        "arabic oud music traditional melodic",
        "persian tar and santoor classical",
        "turkish darbuka rhythm intense percussion",
        "middle eastern belly dance music",
        "indian sitar raga meditative classical",
        "arabic maqam scales exotic melody",
        "persian classical music radif tradition",
        "turkish sufi music whirling dervish",
        "bollywood film soundtrack dramatic",
        "middle eastern electronic fusion modern",
        "indian tabla solo virtuosic percussion",
        "arabic wedding music celebration",
        "persian pop music modern iranian",
        "turkish folk music saz and voice",
        "indian devotional bhajan spiritual",
        "middle eastern ambient atmospheric",
        "arabic hip hop modern fusion",
        "indian fusion jazz contemporary",
        "persian garden music peaceful",
        "turkish psychedelic rock anatolian",
    ],

    'world': [
        "world music fusion blending global sounds",
        "ethnic percussion ensemble multicultural",
        "global bass electronic world fusion",
        "traditional folk music unknown culture",
        "world ambient soundscape cultural blend",
        "ethnic strings ensemble various cultures",
        "global pop crossover international",
        "tribal music primal rhythms",
        "world jazz fusion multicultural",
        "indigenous music traditional ceremony",
        "world beat dance music global",
        "ethnic vocal harmonies various traditions",
        "world chill relaxation music blend",
        "multicultural orchestra fusion",
        "global roots music authentic",
        "world electronic downtempo fusion",
        "ethnic wind instruments ensemble",
        "world meditation music peaceful",
        "cultural celebration music joyful",
        "world documentary soundtrack evocative",
    ],

    # === GENRES ===
    'boom_bap': [
        "boom bap hip hop beat with dusty vinyl samples",
        "90s golden era hip hop instrumental boom bap",
        "old school hip hop with chopped soul samples",
        "boom bap beat with jazz piano sample",
        "classic east coast hip hop instrumental",
        "boom bap with punchy drums and bass",
        "90s underground hip hop boom bap style",
        "boom bap beat with funk guitar sample",
        "golden age rap instrumental dusty",
        "boom bap with scratching and cuts",
        "ny hip hop boom bap production",
        "boom bap beat with horn stabs",
        "classic hip hop drum break loop",
        "boom bap with mpc style drums",
        "old school rap beat boom bap",
        "boom bap with vinyl crackle texture",
        "90s hip hop instrumental nostalgic",
        "boom bap with deep bass line",
        "classic rap production boom bap",
        "golden era style hip hop beat",
    ],

    'drum_and_bass': [
        "drum and bass with fast breakbeats and deep bass",
        "liquid drum and bass smooth and melodic",
        "jungle music with amen break and bass",
        "neurofunk drum and bass dark and heavy",
        "dnb with rolling drums and sub bass",
        "drum and bass with vocal samples",
        "atmospheric drum and bass ambient",
        "jump up drum and bass energetic",
        "drum and bass with jazz influences",
        "techstep dnb dark industrial",
        "ragga jungle with reggae influence",
        "drum and bass with orchestral elements",
        "minimal drum and bass stripped back",
        "drum and bass with piano melody",
        "halftime dnb slower tempo heavy",
        "drum and bass with guitar riff",
        "intelligent drum and bass complex",
        "drum and bass roller smooth",
        "darkside dnb menacing atmosphere",
        "drum and bass with synth lead",
    ],

    'dubstep': [
        "dubstep with heavy wobble bass and halfstep beat",
        "brostep with aggressive wubs and drops",
        "deep dubstep dark and minimal",
        "dubstep with melodic synth lead",
        "riddim dubstep with repetitive bass",
        "dubstep drop with massive bass wobble",
        "dubstep with orchestral strings",
        "future bass dubstep hybrid bright",
        "dubstep with vocal chops",
        "tearout dubstep aggressive and heavy",
        "dubstep with guitar elements",
        "melodic dubstep emotional build",
        "dubstep with reggae influence",
        "hybrid trap dubstep crossover",
        "dubstep with piano intro",
        "heavy dubstep bass drop intense",
        "dubstep with ambient atmosphere",
        "color bass dubstep experimental",
        "dubstep with hip hop elements",
        "classic 2010 dubstep wobble style",
    ],

    'grunge': [
        "grunge rock with distorted guitar and angst vocals",
        "seattle grunge sound dirty and raw",
        "90s alternative grunge rock heavy",
        "grunge ballad slow and emotional",
        "grunge with heavy distortion and feedback",
        "post-grunge rock radio friendly",
        "grunge punk crossover fast aggressive",
        "grunge with acoustic guitar intro",
        "sludgy grunge metal hybrid",
        "grunge rock with quiet-loud dynamics",
        "pacific northwest grunge authentic",
        "grunge with melodic chorus",
        "dirty grunge guitar riff heavy",
        "grunge alternative rock 90s style",
        "grunge with bass heavy mix",
        "lo-fi grunge raw recording",
        "grunge rock anthem powerful",
        "grunge with string arrangement",
        "noise rock grunge experimental",
        "grunge influenced alternative rock",
    ],

    'indie': [
        "indie rock with jangly guitars and introspective lyrics",
        "indie folk acoustic and intimate",
        "indie pop with catchy hooks bright",
        "indie electronic with synths and drums",
        "lo-fi indie bedroom recording aesthetic",
        "indie rock with post-punk influence",
        "dream pop indie with reverb wash",
        "indie folk rock with banjo",
        "shoegaze indie wall of sound",
        "indie pop punk energetic fun",
        "art rock indie experimental",
        "indie acoustic singer songwriter",
        "indie rock with orchestral elements",
        "garage rock indie raw sound",
        "indie with electronic beats modern",
        "twee indie pop gentle sweet",
        "noise pop indie distorted",
        "indie rock anthem uplifting",
        "chamber pop indie orchestral",
        "slacker rock indie laid back",
    ],

    'jazz': [
        "jazz trio with piano bass and drums improvisation",
        "bebop jazz fast tempo complex harmony",
        "cool jazz west coast smooth relaxed",
        "jazz fusion with electric instruments",
        "swing jazz big band arrangement",
        "modal jazz miles davis inspired",
        "free jazz avant garde experimental",
        "jazz ballad slow and romantic",
        "hard bop jazz soulful groove",
        "jazz with latin percussion influence",
        "contemporary jazz modern sound",
        "jazz guitar trio intimate setting",
        "jazz with brass section arrangement",
        "acid jazz with funk groove",
        "jazz waltz in 3/4 time elegant",
        "jazz blues with soul influence",
        "jazz with vocal scatting",
        "straight ahead jazz traditional",
        "jazz quartet saxophone lead",
        "nu jazz electronic influenced",
    ],

    'punk': [
        "punk rock fast loud and aggressive",
        "classic 77 punk raw and simple",
        "hardcore punk fast and intense",
        "pop punk catchy with attitude",
        "skate punk fast melodic guitars",
        "anarcho punk political message",
        "street punk oi style working class",
        "punk with sing-along chorus",
        "garage punk raw recording",
        "punk rock anthem three chords",
        "crust punk heavy and dark",
        "punk blues influenced rock",
        "post-punk angular and dark",
        "punk with ska influence upbeat",
        "proto-punk early pioneers style",
        "punk with surf rock influence",
        "uk punk 1977 style authentic",
        "punk rock energy raw power",
        "punk with metal crossover",
        "punk with folk acoustic elements",
    ],

    'soul': [
        "classic soul music with horns and strings",
        "motown soul with backup singers",
        "deep soul slow and emotional",
        "northern soul uptempo dancer",
        "southern soul with raw emotion",
        "neo soul modern production",
        "blue-eyed soul white artists style",
        "philadelphia soul lush orchestration",
        "psychedelic soul experimental",
        "soul ballad heartfelt romantic",
        "soul with gospel influence spiritual",
        "soul jazz fusion groovy",
        "memphis soul gritty authentic",
        "soul music call and response",
        "quiet storm soul smooth late night",
        "soul with funk influence groovy",
        "vintage soul 1960s style",
        "soul music powerful vocals",
        "progressive soul modern sound",
        "soul christmas holiday warmth",
    ],

    'trance': [
        "uplifting trance with soaring synth melody",
        "progressive trance with building tension",
        "psytrance with hypnotic bassline",
        "vocal trance with ethereal female voice",
        "goa trance with indian influences",
        "hard trance with driving beat",
        "trance anthem with big breakdown",
        "tech trance minimal and driving",
        "acid trance with 303 bassline",
        "epic trance orchestral elements",
        "trance with piano melody emotional",
        "full on psytrance fast and intense",
        "balearic trance ibiza sunset vibes",
        "trance with guitar lead uplifting",
        "dream trance ethereal atmosphere",
        "trance with tribal percussion",
        "euphoric trance peak time energy",
        "dark psy trance twisted sounds",
        "classic 90s trance nostalgic",
        "trance with orchestral strings",
    ],

    'trap': [
        "trap beat with 808 bass and hi-hat rolls",
        "dark trap moody atmosphere",
        "melodic trap with piano and strings",
        "trap with heavy 808 kick drum",
        "drill trap uk style sliding bass",
        "trap beat with vocal chops",
        "southern trap atlanta style",
        "trap with orchestral elements",
        "hard trap aggressive energy",
        "trap with guitar melody sad",
        "phonk trap dark memphis style",
        "trap beat with synth lead",
        "trap with latin percussion",
        "chill trap laid back vibes",
        "trap metal crossover aggressive",
        "trap beat with flute melody",
        "future trap modern production",
        "trap with choir samples epic",
        "bouncy trap energetic happy",
        "trap beat minimal and hard",
    ],

    # === MOODS & STYLES ===
    'cinematic': [
        "cinematic orchestral score epic and sweeping",
        "film soundtrack dramatic tension building",
        "movie score emotional string section",
        "cinematic trailer music powerful impacts",
        "blockbuster film music action sequence",
        "cinematic ambient atmospheric score",
        "film noir soundtrack jazz influenced",
        "cinematic piano emotional solo",
        "movie underscore subtle tension",
        "epic cinematic brass fanfare",
        "cinematic electronic hybrid modern",
        "film music romantic theme",
        "cinematic percussion action drums",
        "movie soundtrack adventure theme",
        "cinematic strings emotional swell",
        "film score horror suspense",
        "cinematic music triumph victory",
        "documentary soundtrack evocative",
        "cinematic choir powerful vocals",
        "film ending credits emotional",
    ],

    'classical': [
        "classical symphony orchestra full arrangement",
        "baroque chamber music harpsichord and strings",
        "classical piano sonata elegant and refined",
        "string quartet classical intimate performance",
        "classical orchestra romantic era style",
        "classical guitar spanish influenced",
        "opera aria dramatic vocal performance",
        "classical flute and harp duet",
        "symphony orchestra dramatic movement",
        "classical violin solo virtuosic",
        "chamber orchestra baroque style",
        "classical brass ensemble fanfare",
        "piano concerto classical virtuoso",
        "classical woodwind quintet ensemble",
        "romantic classical sweeping strings",
        "classical minimalism repetitive patterns",
        "classical crossover modern elements",
        "sacred classical choral music",
        "classical waltz elegant dance",
        "contemporary classical experimental",
    ],

    'dark_ambient': [
        "dark ambient drone deep and ominous",
        "dark ambient soundscape industrial",
        "dark ambient with distant rumbles",
        "horror ambient creepy atmosphere",
        "dark ambient ritual ceremonial",
        "dark drone music evolving textures",
        "dark ambient with metallic sounds",
        "dark ambient dungeon atmosphere",
        "apocalyptic dark ambient wasteland",
        "dark ambient with ghostly whispers",
        "industrial dark ambient harsh",
        "dark ambient space void endless",
        "dark ambient forest night sounds",
        "dark ambient cathedral reverb",
        "dark ambient tension building",
        "dark ambient underwater deep",
        "dark ambient storm approaching",
        "dark ambient haunted location",
        "dark ambient meditation shadow work",
        "dark ambient cinematic underscore",
    ],

    'romantic': [
        "romantic classical music sweeping strings",
        "romantic piano ballad emotional",
        "romantic orchestral love theme",
        "romantic guitar serenade spanish",
        "romantic film score emotional",
        "romantic waltz elegant dance",
        "romantic chamber music intimate",
        "romantic harp and strings duo",
        "romantic violin solo passionate",
        "romantic jazz ballad late night",
        "romantic pop ballad heartfelt",
        "romantic acoustic guitar gentle",
        "romantic symphony emotional movement",
        "romantic saxophone smooth jazz",
        "romantic wedding music ceremony",
        "romantic dinner music ambient",
        "romantic cello solo deep",
        "romantic flute melody gentle",
        "romantic duet piano and violin",
        "romantic sunset music peaceful",
    ],

    'trailer': [
        "movie trailer music epic build and drop",
        "action trailer powerful brass and percussion",
        "horror trailer tension and dread",
        "epic trailer music choir and orchestra",
        "thriller trailer suspenseful building",
        "sci-fi trailer futuristic and epic",
        "drama trailer emotional strings",
        "adventure trailer exciting and bold",
        "trailer music with massive impact hit",
        "dark trailer ominous atmosphere",
        "superhero trailer powerful and heroic",
        "trailer music building tension release",
        "war trailer epic battle music",
        "fantasy trailer magical and epic",
        "trailer music hybrid orchestral electronic",
        "romantic trailer emotional piano",
        "comedy trailer playful and fun",
        "trailer music with vocal elements",
        "blockbuster trailer massive production",
        "indie film trailer understated emotional",
    ],
}

# =============================================================================
# EMPTY SFX CATEGORIES - Need content generation
# =============================================================================

SFX_PROMPTS = {
    'error': [
        "error sound effect buzzer wrong answer game show",
        "computer error beep system failure alert",
        "error notification negative feedback sound",
        "wrong answer buzzer quiz show sound effect",
        "error alert warning beep digital",
        "access denied error sound electronic",
        "system error crash sound effect",
        "error beep short harsh negative",
        "invalid input error sound effect",
        "error notification app alert sound",
        "wrong buzzer sound game incorrect",
        "error tone digital system alert",
        "negative feedback sound effect error",
        "error chime descending notes fail",
        "computer error glitch sound effect",
        "error alert harsh buzzer sound",
        "wrong sound effect game over",
        "error notification mobile app alert",
        "failure sound effect system error",
        "error beep electronic harsh negative",
        "incorrect answer sound quiz game",
        "error alert warning siren short",
        "system failure sound effect digital",
        "error notification descending tone",
        "wrong input buzzer sound effect",
        "error sound harsh digital beep",
        "negative alert sound effect error",
        "error chime system notification",
        "access error sound denied alert",
        "error tone short negative feedback",
    ],

    'paper': [
        "paper rustling sound effect handling documents",
        "page turning book reading sound effect",
        "paper crumpling sound effect crushing paper",
        "paper tearing ripping sound effect",
        "paper shuffling stack of documents",
        "newspaper page turning crackling sound",
        "paper folding crisp creasing sound",
        "paper sliding across desk surface",
        "paper flipping through pages fast",
        "cardboard box opening sound effect",
        "paper cutting scissors through sheet",
        "paper falling floating to floor",
        "paper bag crinkling rustling sound",
        "envelope opening paper tearing",
        "paper writing pencil on surface",
        "paper stack dropping thud sound",
        "origami paper folding crisp",
        "paper wind blowing documents",
        "paper money counting rustling",
        "tissue paper delicate rustling",
        "wrapping paper crinkling gift",
        "paper shredder machine sound effect",
        "paper airplane throwing whoosh",
        "paper fan waving sound effect",
        "cardstock thick paper handling",
        "paper booklet flipping pages",
        "paper receipt printing machine",
        "paper napkin rustling dining",
        "parchment old paper crackling",
        "paper poster unrolling sound",
    ],

    'podcast': [
        "podcast intro music short jingle professional",
        "podcast transition sound effect smooth segue",
        "podcast outro music ending theme",
        "podcast bumper short musical sting",
        "talk show transition sound effect",
        "podcast segment divider sound",
        "interview transition smooth sound effect",
        "podcast logo sound audio branding",
        "podcast ad break transition music",
        "podcast chapter marker sound effect",
        "talk radio transition stinger",
        "podcast intro whoosh transition",
        "podcast ending theme music short",
        "podcast break music interlude",
        "podcast episode intro sound",
        "talk show bumper music short",
        "podcast notification sound effect",
        "podcast subscribe reminder chime",
        "podcast interview intro music",
        "podcast sponsor transition sound",
        "podcast theme music loop short",
        "talk podcast opening jingle",
        "podcast section transition swoosh",
        "podcast news intro sound effect",
        "podcast comedy sting funny",
        "podcast dramatic transition sound",
        "podcast question sound effect thinking",
        "podcast answer reveal sound",
        "podcast recap intro music",
        "podcast finale music ending",
    ],

    'suspense': [
        "suspenseful tension building ambient sound",
        "suspense stinger sudden dramatic hit",
        "tension sound effect rising dread",
        "suspenseful drone ominous atmosphere",
        "suspense reveal dramatic sting",
        "building tension sound effect rising",
        "suspense music underscore thriller",
        "dramatic tension pulse heartbeat",
        "suspense hit sudden impact sound",
        "eerie suspense ambient atmosphere",
        "suspenseful silence before reveal",
        "tension riser building anticipation",
        "suspense drone dark ominous",
        "thriller suspense sound effect",
        "suspense transition dramatic swoosh",
        "tension building percussion subtle",
        "suspense atmosphere creepy ambient",
        "dramatic suspense sting short",
        "suspense sound low rumble rising",
        "thriller tension sound effect",
        "suspense moment frozen time",
        "tension release dramatic hit",
        "suspenseful atmosphere horror",
        "building dread suspense sound",
        "suspense discovery sound effect",
        "tension climax dramatic sting",
        "suspense chase atmosphere music",
        "thriller suspense hit impact",
        "suspense ambient deep drone",
        "tension peak dramatic sound",
    ],

    'tension': [
        "tension drone low rumbling ominous sound",
        "tense atmosphere building anxiety",
        "tension riser sound effect ascending",
        "nervous tension ambient sound",
        "tension building subtle percussion",
        "anxious tension soundscape atmosphere",
        "tension pulse rhythmic unsettling",
        "dramatic tension hit stinger",
        "tension atmosphere film underscore",
        "building tension sound rising pitch",
        "tension drone evolving ominous",
        "stressed tension ambient texture",
        "tension climax sound effect dramatic",
        "subtle tension underlying unease",
        "tension soundscape industrial dark",
        "cinematic tension building score",
        "tension release breath exhale",
        "psychological tension ambient sound",
        "tension music minimal unsettling",
        "high tension wire sound effect",
        "tension moment pause dramatic",
        "escalating tension sound rising",
        "tension underscore subtle threat",
        "nervous energy tension sound",
        "tension atmosphere thriller film",
        "building anxiety tension drone",
        "tension hit sudden impact",
        "creeping tension slow build",
        "tension resolution sound release",
        "dark tension ambient atmosphere",
    ],

    'typing': [
        "typing on keyboard mechanical keys clicking",
        "keyboard typing fast rapid keystrokes",
        "typing sound effect computer keyboard",
        "mechanical keyboard typing satisfying clicks",
        "laptop keyboard typing soft keys",
        "typewriter typing old machine clacking",
        "typing single keystroke keyboard press",
        "keyboard typing rhythmic work sounds",
        "typing on phone touchscreen taps",
        "computer keyboard typing ambient office",
        "typing fast hacker style keyboard",
        "mechanical switches typing clicky",
        "typing slow hunt and peck style",
        "keyboard spacebar press sound effect",
        "typing enter key press confirmation",
        "keyboard backspace delete key sound",
        "typing membrane keyboard soft quiet",
        "typewriter carriage return ding bell",
        "typing on tablet virtual keyboard",
        "keyboard typing with mouse clicks",
        "coding typing fast keyboard sounds",
        "typing essay keyboard writing",
        "keyboard shortcuts typing ctrl keys",
        "typing numbers keypad calculator",
        "mechanical keyboard typing gaming",
        "typing error backspace correction",
        "keyboard typing interview transcription",
        "typing chat messaging keyboard",
        "typewriter keys individual clacks",
        "keyboard typing document writing",
    ],

    'voice': [
        "human voice speaking neutral tone",
        "voice saying yes affirmative response",
        "voice saying no negative response",
        "human humming casual melody",
        "voice coughing clearing throat",
        "voice sneezing achoo sound effect",
        "human yawning tired sound effect",
        "voice whispering quiet speech",
        "voice exclamation surprised reaction",
        "human sigh exhausted relief",
        "voice mumbling unclear speech",
        "voice greeting hello hi sound",
        "human voice thinking hmm sound",
        "voice agreement uh-huh sound",
        "voice disagreement nuh-uh sound",
        "human voice effort grunt",
        "voice surprise gasp intake breath",
        "human whistling casual tune",
        "voice shushing quiet signal",
        "human hiccup sound effect",
        "voice counting numbers sequence",
        "human voice pain ouch expression",
        "voice celebratory woohoo cheer",
        "human throat clearing ahem",
        "voice questioning huh confused",
        "human voice frustration groan",
        "voice impressed wow reaction",
        "human snoring sleeping sound",
        "voice beckoning come here",
        "human burp sound effect casual",
    ],

    'workout': [
        "workout timer beep interval training",
        "exercise countdown timer sound effect",
        "gym workout start bell sound",
        "fitness timer beep rest period",
        "workout complete success sound effect",
        "exercise transition sound effect beep",
        "gym timer countdown ticking",
        "workout interval change notification",
        "fitness achievement sound effect",
        "exercise round start bell ding",
        "workout rest timer sound effect",
        "gym equipment weights clanking",
        "treadmill running machine sound",
        "workout motivation sound effect",
        "exercise breathing heavy exertion",
        "gym ambient workout atmosphere",
        "fitness countdown final seconds",
        "workout halfway notification sound",
        "exercise complete celebration sound",
        "gym locker room ambient sound",
        "workout jump rope whoosh sound",
        "fitness heartbeat pulse sound",
        "exercise mat footsteps impact",
        "gym music transition sound",
        "workout timer warning sound",
        "exercise equipment hydraulic sound",
        "gym punching bag impact sound",
        "workout stretching ambient sound",
        "fitness water bottle drinking",
        "exercise recovery timer beep",
    ],

    'youtube': [
        "youtube intro sound effect short jingle",
        "subscribe notification bell sound effect",
        "like button click sound effect",
        "youtube outro music short ending",
        "video transition whoosh sound effect",
        "youtube notification sound alert",
        "channel intro music energetic short",
        "video segment transition sound",
        "youtube bell notification subscribe",
        "content creator intro jingle",
        "video end screen music short",
        "youtube popup notification sound",
        "vlog transition sound effect smooth",
        "video chapter marker sound",
        "youtube comment notification ding",
        "creator logo audio branding",
        "video intro explosion impact",
        "youtube subscribe animation sound",
        "tutorial transition sound effect",
        "video montage transition whoosh",
        "youtube streaming notification sound",
        "gaming video intro sound effect",
        "vlog music transition upbeat",
        "youtube short vertical video sound",
        "video outro subscribe reminder",
        "content transition smooth swoosh",
        "youtube reveal sound effect dramatic",
        "video highlight notification sound",
        "creator catchphrase intro sound",
        "youtube merchandise promo jingle",
    ],
}


def get_all_prompts():
    """Return all prompts organized by category."""
    return {
        'music': MUSIC_PROMPTS,
        'sfx': SFX_PROMPTS
    }


def get_prompts_for_category(category, model_type='auto'):
    """Get all prompts for a specific category."""
    if model_type == 'auto':
        if category in MUSIC_PROMPTS:
            return MUSIC_PROMPTS[category]
        elif category in SFX_PROMPTS:
            return SFX_PROMPTS[category]
        return []
    elif model_type == 'music':
        return MUSIC_PROMPTS.get(category, [])
    else:
        return SFX_PROMPTS.get(category, [])


def get_random_prompt(category, model_type='auto'):
    """Get a random prompt for a category."""
    prompts = get_prompts_for_category(category, model_type)
    return random.choice(prompts) if prompts else None


def get_category_stats():
    """Get statistics about prompts per category."""
    stats = {
        'music': {cat: len(prompts) for cat, prompts in MUSIC_PROMPTS.items()},
        'sfx': {cat: len(prompts) for cat, prompts in SFX_PROMPTS.items()}
    }
    stats['music_total'] = sum(stats['music'].values())
    stats['sfx_total'] = sum(stats['sfx'].values())
    stats['total'] = stats['music_total'] + stats['sfx_total']
    return stats


if __name__ == '__main__':
    stats = get_category_stats()
    print("=== Prompt Statistics ===")
    print(f"\nMusic Categories ({len(MUSIC_PROMPTS)}):")
    for cat, count in sorted(stats['music'].items()):
        print(f"  {cat}: {count} prompts")
    print(f"  TOTAL: {stats['music_total']} music prompts")

    print(f"\nSFX Categories ({len(SFX_PROMPTS)}):")
    for cat, count in sorted(stats['sfx'].items()):
        print(f"  {cat}: {count} prompts")
    print(f"  TOTAL: {stats['sfx_total']} SFX prompts")

    print(f"\n=== GRAND TOTAL: {stats['total']} prompts ===")
