#!/usr/bin/env python3
"""
Comprehensive voice library generator.
Generates a complete library of speech samples for a specific voice.

Usage:
    python generate_voice_library.py                    # Uses default voice
    python generate_voice_library.py en_GB-vctk-medium  # Specify voice
    python generate_voice_library.py --list-voices      # List available voices
    python generate_voice_library.py --dry-run          # Show prompts without generating
"""

import requests
import time
import json
import sys
import argparse

BASE_URL = "http://localhost:5309"

# =============================================================================
# CONFIGURATION - Change these to customize generation
# =============================================================================

DEFAULT_VOICE = "en_GB-vctk-medium"  # British female voice

# Voice metadata (for tagging)
VOICE_METADATA = {
    'en_GB-vctk-medium': {'gender': 'female', 'accent': 'british', 'style': 'natural'},
    'en_US-ryan-medium': {'gender': 'male', 'accent': 'american', 'style': 'natural'},
    'en_US-amy-medium': {'gender': 'female', 'accent': 'american', 'style': 'natural'},
    'en_US-joe-medium': {'gender': 'male', 'accent': 'american', 'style': 'professional'},
    'en_US-lessac-medium': {'gender': 'female', 'accent': 'american', 'style': 'professional'},
    'en_GB-alan-medium': {'gender': 'male', 'accent': 'british', 'style': 'professional'},
    'en_GB-jenny_dioco-medium': {'gender': 'female', 'accent': 'british', 'style': 'professional'},
    'en_GB-cori-medium': {'gender': 'female', 'accent': 'british', 'style': 'natural'},
    'en_GB-northern_english_male-medium': {'gender': 'male', 'accent': 'british', 'style': 'casual'},
}

# =============================================================================
# COMPREHENSIVE PROMPT LIBRARY
# Each entry: (text, [categories])
# =============================================================================

PROMPTS = {
    # =========================================================================
    # NUMBERS & COUNTING
    # =========================================================================
    'numbers_basic': [
        ("Zero.", ['numbers']),
        ("One.", ['numbers']),
        ("Two.", ['numbers']),
        ("Three.", ['numbers']),
        ("Four.", ['numbers']),
        ("Five.", ['numbers']),
        ("Six.", ['numbers']),
        ("Seven.", ['numbers']),
        ("Eight.", ['numbers']),
        ("Nine.", ['numbers']),
        ("Ten.", ['numbers']),
        ("Eleven.", ['numbers']),
        ("Twelve.", ['numbers']),
        ("Thirteen.", ['numbers']),
        ("Fourteen.", ['numbers']),
        ("Fifteen.", ['numbers']),
        ("Sixteen.", ['numbers']),
        ("Seventeen.", ['numbers']),
        ("Eighteen.", ['numbers']),
        ("Nineteen.", ['numbers']),
        ("Twenty.", ['numbers']),
        ("Twenty-one.", ['numbers']),
        ("Twenty-two.", ['numbers']),
        ("Twenty-three.", ['numbers']),
        ("Twenty-four.", ['numbers']),
        ("Twenty-five.", ['numbers']),
        ("Thirty.", ['numbers']),
        ("Forty.", ['numbers']),
        ("Fifty.", ['numbers']),
        ("Sixty.", ['numbers']),
        ("Seventy.", ['numbers']),
        ("Eighty.", ['numbers']),
        ("Ninety.", ['numbers']),
        ("One hundred.", ['numbers']),
        ("Two hundred.", ['numbers']),
        ("Five hundred.", ['numbers']),
        ("One thousand.", ['numbers']),
        ("Ten thousand.", ['numbers']),
        ("One hundred thousand.", ['numbers']),
        ("One million.", ['numbers']),
        ("One billion.", ['numbers']),
    ],

    'numbers_ordinal': [
        ("First.", ['numbers']),
        ("Second.", ['numbers']),
        ("Third.", ['numbers']),
        ("Fourth.", ['numbers']),
        ("Fifth.", ['numbers']),
        ("Sixth.", ['numbers']),
        ("Seventh.", ['numbers']),
        ("Eighth.", ['numbers']),
        ("Ninth.", ['numbers']),
        ("Tenth.", ['numbers']),
        ("Eleventh.", ['numbers']),
        ("Twelfth.", ['numbers']),
        ("Thirteenth.", ['numbers']),
        ("Fourteenth.", ['numbers']),
        ("Fifteenth.", ['numbers']),
        ("Twentieth.", ['numbers']),
        ("Thirtieth.", ['numbers']),
        ("Fortieth.", ['numbers']),
        ("Fiftieth.", ['numbers']),
        ("Hundredth.", ['numbers']),
        ("Thousandth.", ['numbers']),
    ],

    'counting': [
        ("One, two, three.", ['counting', 'numbers']),
        ("One, two, three, four, five.", ['counting', 'numbers']),
        ("One, two, three, four, five, six, seven, eight, nine, ten.", ['counting', 'numbers']),
        ("Counting down: five, four, three, two, one.", ['counting', 'numbers']),
        ("Three, two, one, go!", ['counting', 'numbers']),
        ("Ten, nine, eight, seven, six, five, four, three, two, one, zero.", ['counting', 'numbers']),
        ("Ten, nine, eight, seven, six, five, four, three, two, one, liftoff!", ['counting', 'numbers']),
        ("Five, four, three, two, one, happy new year!", ['counting', 'numbers']),
        ("First, second, third.", ['counting', 'numbers']),
        ("A, B, C, D, E.", ['counting']),
        ("One plus one equals two.", ['counting', 'numbers']),
        ("Two plus two equals four.", ['counting', 'numbers']),
        ("Three times three equals nine.", ['counting', 'numbers']),
    ],

    # =========================================================================
    # TIME & DATE
    # =========================================================================
    'time': [
        ("It is now twelve o'clock.", ['time']),
        ("The time is one o'clock.", ['time']),
        ("The time is two o'clock.", ['time']),
        ("The time is three o'clock.", ['time']),
        ("The time is four o'clock.", ['time']),
        ("The time is five o'clock.", ['time']),
        ("The time is six o'clock.", ['time']),
        ("The time is seven o'clock.", ['time']),
        ("The time is eight o'clock.", ['time']),
        ("The time is nine o'clock.", ['time']),
        ("The time is ten o'clock.", ['time']),
        ("The time is eleven o'clock.", ['time']),
        ("It's noon.", ['time']),
        ("It's midnight.", ['time']),
        ("The time is three thirty.", ['time']),
        ("Five forty-five PM.", ['time']),
        ("It's quarter past nine.", ['time']),
        ("It's quarter to ten.", ['time']),
        ("Half past two.", ['time']),
        ("Half past seven.", ['time']),
        ("Ten minutes to midnight.", ['time']),
        ("Five minutes past the hour.", ['time']),
        ("The current time is eight fifteen AM.", ['time', 'announcement']),
        ("It's early morning.", ['time']),
        ("It's late afternoon.", ['time']),
        ("It's evening.", ['time']),
        ("It's night time.", ['time']),
        ("You have five minutes remaining.", ['time', 'alert']),
        ("You have one minute remaining.", ['time', 'alert']),
        ("You have thirty seconds remaining.", ['time', 'alert']),
        ("You have ten seconds remaining.", ['time', 'alert']),
        ("Time's up!", ['time', 'alert']),
        ("Time remaining: five minutes.", ['time']),
        ("Time remaining: one minute.", ['time']),
        ("Time elapsed: ten minutes.", ['time']),
        ("In five minutes.", ['time']),
        ("In one hour.", ['time']),
        ("Right now.", ['time']),
        ("Later today.", ['time']),
        ("Tomorrow.", ['time']),
        ("Yesterday.", ['time']),
    ],

    'date': [
        ("Today is Monday.", ['date']),
        ("Today is Tuesday.", ['date']),
        ("Today is Wednesday.", ['date']),
        ("Today is Thursday.", ['date']),
        ("Today is Friday.", ['date']),
        ("Today is Saturday.", ['date']),
        ("Today is Sunday.", ['date']),
        ("It's the weekend.", ['date']),
        ("Monday, January first.", ['date']),
        ("Tuesday, February fourteenth.", ['date']),
        ("Wednesday, March fifteenth.", ['date']),
        ("Thursday, April first.", ['date']),
        ("Friday, May fifth.", ['date']),
        ("Saturday, June twentieth.", ['date']),
        ("Sunday, July fourth.", ['date']),
        ("August thirty-first.", ['date']),
        ("September first.", ['date']),
        ("October thirty-first.", ['date']),
        ("November eleventh.", ['date']),
        ("December twenty-fifth.", ['date']),
        ("Happy New Year!", ['date', 'greeting']),
        ("Happy Valentine's Day!", ['date', 'greeting']),
        ("Happy Easter!", ['date', 'greeting']),
        ("Happy Independence Day!", ['date', 'greeting']),
        ("Happy Halloween!", ['date', 'greeting']),
        ("Happy Thanksgiving!", ['date', 'greeting']),
        ("Merry Christmas!", ['date', 'greeting']),
        ("Happy Holidays!", ['date', 'greeting']),
        ("Happy Birthday!", ['date', 'greeting']),
        ("Happy Anniversary!", ['date', 'greeting']),
        ("This week.", ['date']),
        ("Next week.", ['date']),
        ("Last week.", ['date']),
        ("This month.", ['date']),
        ("Next month.", ['date']),
        ("This year.", ['date']),
    ],

    # =========================================================================
    # CURRENCY & MONEY
    # =========================================================================
    'currency': [
        ("One dollar.", ['currency', 'numbers']),
        ("Five dollars.", ['currency', 'numbers']),
        ("Ten dollars.", ['currency', 'numbers']),
        ("Twenty dollars.", ['currency', 'numbers']),
        ("Fifty dollars.", ['currency', 'numbers']),
        ("One hundred dollars.", ['currency', 'numbers']),
        ("Five hundred dollars.", ['currency', 'numbers']),
        ("One thousand dollars.", ['currency', 'numbers']),
        ("One cent.", ['currency', 'numbers']),
        ("Five cents.", ['currency', 'numbers']),
        ("Ten cents.", ['currency', 'numbers']),
        ("Twenty-five cents.", ['currency', 'numbers']),
        ("Fifty cents.", ['currency', 'numbers']),
        ("Ninety-nine cents.", ['currency', 'numbers']),
        ("One dollar and fifty cents.", ['currency', 'numbers']),
        ("Five dollars and ninety-nine cents.", ['currency', 'numbers']),
        ("That will be twenty-three fifty.", ['currency', 'numbers']),
        ("The total is one hundred dollars.", ['currency', 'numbers']),
        ("Your change is five dollars and twenty-five cents.", ['currency', 'numbers']),
        ("Fifty percent off.", ['currency', 'numbers']),
        ("Twenty percent discount.", ['currency', 'numbers']),
        ("Buy one, get one free.", ['currency', 'commercial']),
        ("Your balance is zero.", ['currency', 'numbers']),
        ("Insufficient funds.", ['currency', 'alert']),
        ("Payment successful.", ['currency', 'confirmation']),
        ("Payment declined.", ['currency', 'denial']),
        ("Transaction complete.", ['currency', 'confirmation']),
        ("One pound.", ['currency', 'numbers']),
        ("Five pounds.", ['currency', 'numbers']),
        ("Ten euros.", ['currency', 'numbers']),
        ("Free of charge.", ['currency']),
        ("No additional cost.", ['currency']),
    ],

    # =========================================================================
    # PHONE & CONTACT
    # =========================================================================
    'phone': [
        ("Please call five five five, one two three four.", ['phone_number']),
        ("Dial nine one one for emergencies.", ['phone_number', 'alert']),
        ("Press one for English.", ['phone_number', 'prompt']),
        ("Press two for Spanish.", ['phone_number', 'prompt']),
        ("Press zero to speak with an operator.", ['phone_number', 'prompt']),
        ("Please hold.", ['phone_number']),
        ("Please hold, your call is important to us.", ['phone_number']),
        ("All of our operators are currently busy.", ['phone_number']),
        ("Your call is being transferred.", ['phone_number']),
        ("You are caller number five in the queue.", ['phone_number']),
        ("The estimated wait time is ten minutes.", ['phone_number', 'time']),
        ("Please leave a message after the tone.", ['phone_number']),
        ("The mailbox is full.", ['phone_number']),
        ("This call may be recorded for quality assurance.", ['phone_number']),
        ("Goodbye.", ['phone_number', 'farewell']),
        ("Thank you for calling.", ['phone_number', 'thanks']),
        ("Please enter your PIN.", ['phone_number', 'prompt']),
        ("Invalid entry. Please try again.", ['phone_number', 'denial']),
        ("Your account balance is.", ['phone_number']),
        ("For billing inquiries, press three.", ['phone_number', 'prompt']),
        ("For technical support, press four.", ['phone_number', 'prompt']),
        ("To repeat this menu, press nine.", ['phone_number', 'prompt']),
        ("To return to the main menu, press star.", ['phone_number', 'prompt']),
    ],

    # =========================================================================
    # GREETINGS
    # =========================================================================
    'greeting': [
        ("Hello.", ['greeting']),
        ("Hi.", ['greeting']),
        ("Hi there!", ['greeting']),
        ("Hey.", ['greeting']),
        ("Hey there!", ['greeting']),
        ("Good morning.", ['greeting']),
        ("Good afternoon.", ['greeting']),
        ("Good evening.", ['greeting']),
        ("Good day.", ['greeting']),
        ("Hey, how's it going?", ['greeting']),
        ("How are you?", ['greeting']),
        ("How are you doing?", ['greeting']),
        ("How are you today?", ['greeting']),
        ("What's up?", ['greeting']),
        ("How's everything?", ['greeting']),
        ("Nice to see you.", ['greeting']),
        ("Nice to meet you.", ['greeting']),
        ("Pleased to meet you.", ['greeting']),
        ("It's nice to meet you.", ['greeting']),
        ("Welcome.", ['greeting']),
        ("Welcome back.", ['greeting']),
        ("Welcome aboard.", ['greeting']),
        ("Welcome home.", ['greeting']),
        ("Welcome to our store.", ['greeting', 'commercial']),
        ("Welcome to the show.", ['greeting', 'announcement']),
        ("Greetings.", ['greeting']),
        ("Greetings and salutations.", ['greeting']),
        ("Hello, and welcome.", ['greeting']),
        ("Hi, I'm here to help.", ['greeting']),
        ("Hello, how may I help you?", ['greeting', 'prompt']),
        ("Good to see you again.", ['greeting']),
        ("Long time no see.", ['greeting']),
        ("It's been a while.", ['greeting']),
    ],

    # =========================================================================
    # FAREWELLS
    # =========================================================================
    'farewell': [
        ("Goodbye.", ['farewell']),
        ("Bye.", ['farewell']),
        ("Bye bye.", ['farewell']),
        ("Bye for now.", ['farewell']),
        ("See you.", ['farewell']),
        ("See you later.", ['farewell']),
        ("See you soon.", ['farewell']),
        ("See you tomorrow.", ['farewell']),
        ("See you next time.", ['farewell']),
        ("Take care.", ['farewell']),
        ("Take care of yourself.", ['farewell']),
        ("Have a nice day.", ['farewell']),
        ("Have a good day.", ['farewell']),
        ("Have a great day.", ['farewell']),
        ("Have a wonderful day.", ['farewell']),
        ("Have a good one.", ['farewell']),
        ("Have a good night.", ['farewell']),
        ("Have a good weekend.", ['farewell']),
        ("Have fun.", ['farewell']),
        ("Have a safe trip.", ['farewell']),
        ("Until next time.", ['farewell']),
        ("Until we meet again.", ['farewell']),
        ("Catch you later.", ['farewell']),
        ("Talk to you later.", ['farewell']),
        ("Talk soon.", ['farewell']),
        ("Later.", ['farewell']),
        ("Peace.", ['farewell']),
        ("Peace out.", ['farewell']),
        ("Farewell.", ['farewell']),
        ("So long.", ['farewell']),
        ("Cheers.", ['farewell']),
        ("All the best.", ['farewell']),
        ("Best wishes.", ['farewell']),
        ("Good luck.", ['farewell']),
        ("Godspeed.", ['farewell']),
        ("Stay safe.", ['farewell']),
        ("Keep in touch.", ['farewell']),
    ],

    # =========================================================================
    # THANKS & APPRECIATION
    # =========================================================================
    'thanks': [
        ("Thank you.", ['thanks']),
        ("Thanks.", ['thanks']),
        ("Thanks a lot.", ['thanks']),
        ("Thank you very much.", ['thanks']),
        ("Thank you so much.", ['thanks']),
        ("Thanks so much.", ['thanks']),
        ("Many thanks.", ['thanks']),
        ("Thanks a million.", ['thanks']),
        ("I appreciate it.", ['thanks']),
        ("I really appreciate it.", ['thanks']),
        ("I appreciate your help.", ['thanks']),
        ("I appreciate your time.", ['thanks']),
        ("Thanks for your help.", ['thanks']),
        ("Thanks for your patience.", ['thanks']),
        ("Thanks for understanding.", ['thanks']),
        ("Thanks for everything.", ['thanks']),
        ("Thanks for listening.", ['thanks']),
        ("Thanks for watching.", ['thanks']),
        ("Thanks for joining us.", ['thanks']),
        ("Thanks for coming.", ['thanks']),
        ("Thanks for your support.", ['thanks']),
        ("Thank you for your business.", ['thanks']),
        ("Thank you for choosing us.", ['thanks']),
        ("You're welcome.", ['thanks']),
        ("You're very welcome.", ['thanks']),
        ("No problem.", ['thanks']),
        ("No worries.", ['thanks']),
        ("Not at all.", ['thanks']),
        ("Don't mention it.", ['thanks']),
        ("It's my pleasure.", ['thanks']),
        ("My pleasure.", ['thanks']),
        ("Glad to help.", ['thanks']),
        ("Happy to help.", ['thanks']),
        ("Anytime.", ['thanks']),
        ("Of course.", ['thanks']),
        ("Sure thing.", ['thanks']),
    ],

    # =========================================================================
    # APOLOGIES
    # =========================================================================
    'apology': [
        ("Sorry.", ['apology']),
        ("I'm sorry.", ['apology']),
        ("I'm so sorry.", ['apology']),
        ("I'm really sorry.", ['apology']),
        ("I apologize.", ['apology']),
        ("My apologies.", ['apology']),
        ("Please forgive me.", ['apology']),
        ("Excuse me.", ['apology']),
        ("Pardon me.", ['apology']),
        ("I beg your pardon.", ['apology']),
        ("Sorry about that.", ['apology']),
        ("Sorry for the inconvenience.", ['apology']),
        ("Sorry for the delay.", ['apology']),
        ("Sorry for the wait.", ['apology']),
        ("Sorry for the confusion.", ['apology']),
        ("Sorry for any trouble.", ['apology']),
        ("That's my fault.", ['apology']),
        ("My mistake.", ['apology']),
        ("My bad.", ['apology']),
        ("I didn't mean to.", ['apology']),
        ("It won't happen again.", ['apology']),
        ("No offense intended.", ['apology']),
        ("Apologies for the delay.", ['apology']),
        ("We apologize for any inconvenience.", ['apology', 'announcement']),
    ],

    # =========================================================================
    # CONFIRMATION & AGREEMENT
    # =========================================================================
    'confirmation': [
        ("Yes.", ['confirmation']),
        ("Yeah.", ['confirmation']),
        ("Yep.", ['confirmation']),
        ("Yup.", ['confirmation']),
        ("Yes, please.", ['confirmation']),
        ("Yes, that's correct.", ['confirmation']),
        ("Correct.", ['confirmation']),
        ("That's correct.", ['confirmation']),
        ("That's right.", ['confirmation']),
        ("Right.", ['confirmation']),
        ("Exactly.", ['confirmation']),
        ("Precisely.", ['confirmation']),
        ("Affirmative.", ['confirmation']),
        ("Confirmed.", ['confirmation']),
        ("Acknowledged.", ['confirmation']),
        ("Roger that.", ['confirmation']),
        ("Copy that.", ['confirmation']),
        ("Ten-four.", ['confirmation']),
        ("Okay.", ['confirmation']),
        ("OK.", ['confirmation']),
        ("Alright.", ['confirmation']),
        ("All right.", ['confirmation']),
        ("Fine.", ['confirmation']),
        ("Sure.", ['confirmation']),
        ("Sure thing.", ['confirmation']),
        ("Absolutely.", ['confirmation']),
        ("Definitely.", ['confirmation']),
        ("Certainly.", ['confirmation']),
        ("Of course.", ['confirmation']),
        ("Indeed.", ['confirmation']),
        ("Agreed.", ['confirmation']),
        ("I agree.", ['confirmation']),
        ("That works.", ['confirmation']),
        ("Sounds good.", ['confirmation']),
        ("Perfect.", ['confirmation']),
        ("Great.", ['confirmation']),
        ("Excellent.", ['confirmation']),
        ("Wonderful.", ['confirmation']),
        ("Got it.", ['confirmation']),
        ("Understood.", ['confirmation']),
        ("I understand.", ['confirmation']),
        ("Will do.", ['confirmation']),
        ("Consider it done.", ['confirmation']),
        ("No problem.", ['confirmation']),
        ("Done.", ['confirmation']),
        ("Complete.", ['confirmation']),
        ("Completed.", ['confirmation']),
        ("Success.", ['confirmation']),
        ("Successful.", ['confirmation']),
        ("Approved.", ['confirmation']),
        ("Accepted.", ['confirmation']),
        ("Valid.", ['confirmation']),
        ("Verified.", ['confirmation']),
        ("Authenticated.", ['confirmation']),
        ("Authorized.", ['confirmation']),
        ("Access granted.", ['confirmation']),
        ("Permission granted.", ['confirmation']),
        ("Request approved.", ['confirmation']),
        ("Operation successful.", ['confirmation']),
        ("Task complete.", ['confirmation']),
        ("Action completed successfully.", ['confirmation']),
    ],

    # =========================================================================
    # DENIAL & DISAGREEMENT
    # =========================================================================
    'denial': [
        ("No.", ['denial']),
        ("Nope.", ['denial']),
        ("Nah.", ['denial']),
        ("No, thanks.", ['denial']),
        ("No, thank you.", ['denial']),
        ("Not really.", ['denial']),
        ("Not quite.", ['denial']),
        ("Not exactly.", ['denial']),
        ("Negative.", ['denial']),
        ("Incorrect.", ['denial']),
        ("That's incorrect.", ['denial']),
        ("That's not correct.", ['denial']),
        ("That's not right.", ['denial']),
        ("That's wrong.", ['denial']),
        ("Wrong.", ['denial']),
        ("I don't think so.", ['denial']),
        ("I disagree.", ['denial']),
        ("I'm afraid not.", ['denial']),
        ("Unfortunately, no.", ['denial']),
        ("Sorry, no.", ['denial']),
        ("Denied.", ['denial']),
        ("Request denied.", ['denial']),
        ("Access denied.", ['denial']),
        ("Permission denied.", ['denial']),
        ("Unauthorized.", ['denial']),
        ("Invalid.", ['denial']),
        ("Error.", ['denial']),
        ("Failed.", ['denial']),
        ("Failure.", ['denial']),
        ("Unsuccessful.", ['denial']),
        ("That's not possible.", ['denial']),
        ("Sorry, that's not possible.", ['denial']),
        ("I can't do that.", ['denial']),
        ("That's not allowed.", ['denial']),
        ("Not permitted.", ['denial']),
        ("Forbidden.", ['denial']),
        ("Rejected.", ['denial']),
        ("Declined.", ['denial']),
        ("Cancelled.", ['denial']),
        ("Canceled.", ['denial']),
        ("Aborted.", ['denial']),
        ("Stopped.", ['denial']),
        ("Blocked.", ['denial']),
        ("Restricted.", ['denial']),
        ("Not available.", ['denial']),
        ("Unavailable.", ['denial']),
        ("Not found.", ['denial']),
        ("Does not exist.", ['denial']),
        ("Invalid input.", ['denial']),
        ("Invalid entry.", ['denial']),
        ("Invalid selection.", ['denial']),
        ("Try again.", ['denial']),
        ("Please try again.", ['denial']),
        ("Please try again later.", ['denial']),
    ],

    # =========================================================================
    # QUESTIONS
    # =========================================================================
    'question': [
        ("What?", ['question']),
        ("Why?", ['question']),
        ("How?", ['question']),
        ("When?", ['question']),
        ("Where?", ['question']),
        ("Who?", ['question']),
        ("Which?", ['question']),
        ("Really?", ['question']),
        ("Seriously?", ['question']),
        ("Are you sure?", ['question']),
        ("Are you certain?", ['question']),
        ("Is that so?", ['question']),
        ("Is that right?", ['question']),
        ("Is that correct?", ['question']),
        ("Can you repeat that?", ['question']),
        ("Could you repeat that?", ['question']),
        ("What did you say?", ['question']),
        ("Sorry, what was that?", ['question']),
        ("Pardon?", ['question']),
        ("Excuse me?", ['question']),
        ("I'm sorry?", ['question']),
        ("What do you mean?", ['question']),
        ("How so?", ['question']),
        ("Why not?", ['question']),
        ("Why is that?", ['question']),
        ("What happened?", ['question']),
        ("What's wrong?", ['question']),
        ("What's the problem?", ['question']),
        ("What's going on?", ['question']),
        ("What's happening?", ['question']),
        ("What's next?", ['question']),
        ("What now?", ['question']),
        ("What should I do?", ['question']),
        ("What would you like?", ['question']),
        ("What would you like to do?", ['question']),
        ("How can I help?", ['question']),
        ("How may I help you?", ['question']),
        ("Is there anything else?", ['question']),
        ("Anything else?", ['question']),
        ("Need anything else?", ['question']),
        ("Do you understand?", ['question']),
        ("Does that make sense?", ['question']),
        ("Is that clear?", ['question']),
        ("Any questions?", ['question']),
        ("Do you have any questions?", ['question']),
        ("Ready?", ['question']),
        ("Are you ready?", ['question']),
        ("Shall we begin?", ['question']),
        ("Shall we continue?", ['question']),
        ("Would you like to continue?", ['question']),
        ("May I?", ['question']),
        ("Can I?", ['question']),
        ("Should I?", ['question']),
        ("Shall I?", ['question']),
    ],

    # =========================================================================
    # DIRECTIONS & NAVIGATION
    # =========================================================================
    'directions': [
        ("Turn left.", ['directions']),
        ("Turn right.", ['directions']),
        ("Go straight.", ['directions']),
        ("Go straight ahead.", ['directions']),
        ("Continue straight.", ['directions']),
        ("Keep going.", ['directions']),
        ("Keep straight.", ['directions']),
        ("Make a U-turn.", ['directions']),
        ("Make a left turn.", ['directions']),
        ("Make a right turn.", ['directions']),
        ("Bear left.", ['directions']),
        ("Bear right.", ['directions']),
        ("Merge left.", ['directions']),
        ("Merge right.", ['directions']),
        ("Stay in the left lane.", ['directions']),
        ("Stay in the right lane.", ['directions']),
        ("Take the next exit.", ['directions']),
        ("Take the second exit.", ['directions']),
        ("Exit here.", ['directions']),
        ("In one hundred meters, turn left.", ['directions']),
        ("In two hundred meters, turn right.", ['directions']),
        ("In five hundred meters.", ['directions']),
        ("In one kilometer.", ['directions']),
        ("In one mile.", ['directions']),
        ("Continue for two miles.", ['directions']),
        ("Continue for five kilometers.", ['directions']),
        ("Your destination is on the left.", ['directions']),
        ("Your destination is on the right.", ['directions']),
        ("Your destination is ahead.", ['directions']),
        ("You have arrived.", ['directions']),
        ("You have arrived at your destination.", ['directions']),
        ("Recalculating.", ['directions']),
        ("Recalculating route.", ['directions']),
        ("Route updated.", ['directions']),
        ("Follow the road.", ['directions']),
        ("Stay on this road.", ['directions']),
        ("Enter the roundabout.", ['directions']),
        ("Exit the roundabout.", ['directions']),
        ("Take the first exit at the roundabout.", ['directions']),
        ("Take the second exit at the roundabout.", ['directions']),
        ("Take the third exit at the roundabout.", ['directions']),
        ("Cross the bridge.", ['directions']),
        ("Go through the tunnel.", ['directions']),
        ("Pass the traffic light.", ['directions']),
        ("At the intersection.", ['directions']),
        ("At the junction.", ['directions']),
        ("Speed limit: thirty miles per hour.", ['directions']),
        ("Speed limit: fifty kilometers per hour.", ['directions']),
        ("Caution: speed camera ahead.", ['directions', 'warning']),
        ("Toll road ahead.", ['directions']),
        ("Rest area ahead.", ['directions']),
        ("Gas station ahead.", ['directions']),
        ("Parking available.", ['directions']),
        ("No parking.", ['directions']),
    ],

    # =========================================================================
    # TUTORIALS & INSTRUCTIONS
    # =========================================================================
    'tutorial': [
        ("Step one.", ['tutorial']),
        ("Step two.", ['tutorial']),
        ("Step three.", ['tutorial']),
        ("Step four.", ['tutorial']),
        ("Step five.", ['tutorial']),
        ("Step six.", ['tutorial']),
        ("Step seven.", ['tutorial']),
        ("Step eight.", ['tutorial']),
        ("Step nine.", ['tutorial']),
        ("Step ten.", ['tutorial']),
        ("First step.", ['tutorial']),
        ("Next step.", ['tutorial']),
        ("Final step.", ['tutorial']),
        ("Last step.", ['tutorial']),
        ("First, click the button.", ['tutorial', 'prompt']),
        ("Next, enter your information.", ['tutorial', 'prompt']),
        ("Then, click submit.", ['tutorial', 'prompt']),
        ("Finally, press submit.", ['tutorial', 'prompt']),
        ("Let me show you how.", ['tutorial']),
        ("Here's how it works.", ['tutorial']),
        ("Follow these instructions.", ['tutorial']),
        ("Follow these steps.", ['tutorial']),
        ("Do the following.", ['tutorial']),
        ("Start by.", ['tutorial']),
        ("Begin by.", ['tutorial']),
        ("To get started.", ['tutorial']),
        ("To begin.", ['tutorial']),
        ("The first thing you need to do.", ['tutorial']),
        ("Now we're going to.", ['tutorial']),
        ("Watch carefully.", ['tutorial']),
        ("Pay attention.", ['tutorial']),
        ("Here's a tip.", ['tutorial']),
        ("Pro tip.", ['tutorial']),
        ("Quick tip.", ['tutorial']),
        ("Remember.", ['tutorial']),
        ("Don't forget.", ['tutorial']),
        ("Keep in mind.", ['tutorial']),
        ("Note that.", ['tutorial']),
        ("Important.", ['tutorial']),
        ("This is important.", ['tutorial']),
        ("Make sure to.", ['tutorial']),
        ("Be sure to.", ['tutorial']),
        ("You'll want to.", ['tutorial']),
        ("You'll need to.", ['tutorial']),
        ("Once you've done that.", ['tutorial']),
        ("After that.", ['tutorial']),
        ("And that's it.", ['tutorial']),
        ("That's all there is to it.", ['tutorial']),
        ("You're all set.", ['tutorial']),
        ("You're done.", ['tutorial']),
        ("Well done.", ['tutorial', 'confirmation']),
        ("Great job.", ['tutorial', 'confirmation']),
        ("Congratulations.", ['tutorial', 'confirmation']),
    ],

    # =========================================================================
    # WARNINGS & ALERTS
    # =========================================================================
    'warning': [
        ("Warning.", ['warning', 'alert']),
        ("Warning!", ['warning', 'alert']),
        ("Caution.", ['warning', 'alert']),
        ("Caution!", ['warning', 'alert']),
        ("Be careful.", ['warning']),
        ("Watch out.", ['warning', 'alert']),
        ("Watch out!", ['warning', 'alert']),
        ("Look out.", ['warning', 'alert']),
        ("Look out!", ['warning', 'alert']),
        ("Danger.", ['warning', 'alert']),
        ("Danger!", ['warning', 'alert']),
        ("Danger ahead.", ['warning', 'alert']),
        ("Hazard ahead.", ['warning', 'alert']),
        ("Please proceed with caution.", ['warning']),
        ("Proceed with caution.", ['warning']),
        ("Handle with care.", ['warning']),
        ("Be advised.", ['warning']),
        ("Please be advised.", ['warning']),
        ("Attention.", ['warning', 'alert']),
        ("Attention!", ['warning', 'alert']),
        ("Attention please.", ['warning', 'alert', 'announcement']),
        ("Alert.", ['alert']),
        ("Alert!", ['alert']),
        ("Critical alert.", ['alert']),
        ("System alert.", ['alert']),
        ("Security alert.", ['alert']),
        ("Important notice.", ['alert', 'announcement']),
        ("Important!", ['alert']),
        ("Notice.", ['alert']),
        ("Emergency.", ['alert']),
        ("Emergency!", ['alert']),
        ("This is an emergency.", ['alert']),
        ("This is not a drill.", ['alert']),
        ("Evacuate immediately.", ['alert']),
        ("Please remain calm.", ['alert']),
        ("Do not panic.", ['alert']),
        ("Fire.", ['alert']),
        ("Fire!", ['alert']),
        ("Intruder.", ['alert']),
        ("Intruder alert.", ['alert']),
        ("Lockdown.", ['alert']),
        ("Lockdown initiated.", ['alert']),
        ("All clear.", ['alert', 'confirmation']),
        ("Situation resolved.", ['alert', 'confirmation']),
        ("Low battery.", ['alert']),
        ("Battery low.", ['alert']),
        ("Critical battery.", ['alert']),
        ("Low fuel.", ['alert']),
        ("Check engine.", ['alert']),
        ("Maintenance required.", ['alert']),
        ("Service required.", ['alert']),
        ("Update available.", ['alert']),
        ("Update required.", ['alert']),
        ("Connection lost.", ['alert']),
        ("Signal lost.", ['alert']),
        ("No signal.", ['alert']),
        ("Weak signal.", ['alert']),
        ("Strong signal.", ['alert', 'confirmation']),
        ("Connection restored.", ['alert', 'confirmation']),
        ("This action cannot be undone.", ['warning']),
        ("Are you sure you want to continue?", ['warning', 'question']),
        ("This will delete all data.", ['warning']),
        ("Permanent action.", ['warning']),
        ("No undo.", ['warning']),
        ("Final warning.", ['warning']),
        ("Last chance.", ['warning']),
        ("You have been warned.", ['warning']),
    ],

    # =========================================================================
    # REMINDERS & NOTIFICATIONS
    # =========================================================================
    'reminder': [
        ("Reminder.", ['reminder']),
        ("This is a reminder.", ['reminder']),
        ("Don't forget.", ['reminder']),
        ("Remember to.", ['reminder']),
        ("Remember to save your work.", ['reminder']),
        ("Remember to take a break.", ['reminder']),
        ("Time for a break.", ['reminder']),
        ("Time to stretch.", ['reminder']),
        ("Stay hydrated.", ['reminder']),
        ("Drink water.", ['reminder']),
        ("Take your medication.", ['reminder']),
        ("Meeting in ten minutes.", ['reminder', 'time']),
        ("Meeting in five minutes.", ['reminder', 'time']),
        ("Meeting starting now.", ['reminder', 'time']),
        ("Your appointment is in one hour.", ['reminder', 'time']),
        ("Appointment reminder.", ['reminder']),
        ("Event starting soon.", ['reminder']),
        ("Task due today.", ['reminder']),
        ("Deadline approaching.", ['reminder']),
        ("Due tomorrow.", ['reminder']),
        ("Overdue.", ['reminder', 'alert']),
        ("Please remember to log out.", ['reminder']),
        ("Save before closing.", ['reminder']),
        ("Backup your data.", ['reminder']),
        ("Check your email.", ['reminder']),
        ("You have unread messages.", ['reminder']),
        ("New message.", ['reminder']),
        ("New email.", ['reminder']),
        ("New notification.", ['reminder']),
        ("You have a new notification.", ['reminder']),
        ("Incoming message.", ['reminder']),
        ("Incoming call.", ['reminder']),
        ("Missed call.", ['reminder']),
        ("Voicemail.", ['reminder']),
        ("New voicemail.", ['reminder']),
        ("Calendar reminder.", ['reminder']),
        ("Birthday today.", ['reminder']),
        ("Anniversary today.", ['reminder']),
    ],

    # =========================================================================
    # PROMPTS & REQUESTS
    # =========================================================================
    'prompt': [
        ("Please enter your password.", ['prompt']),
        ("Please enter your username.", ['prompt']),
        ("Please enter your email.", ['prompt']),
        ("Please enter your name.", ['prompt']),
        ("Enter your name.", ['prompt']),
        ("Enter your password.", ['prompt']),
        ("Enter your PIN.", ['prompt']),
        ("Enter your code.", ['prompt']),
        ("Enter verification code.", ['prompt']),
        ("Type your message here.", ['prompt']),
        ("Type your response.", ['prompt']),
        ("Press any key to continue.", ['prompt']),
        ("Press enter to continue.", ['prompt']),
        ("Click here to proceed.", ['prompt']),
        ("Click to continue.", ['prompt']),
        ("Tap to continue.", ['prompt']),
        ("Swipe to continue.", ['prompt']),
        ("Select an option.", ['prompt']),
        ("Choose an option.", ['prompt']),
        ("Make a selection.", ['prompt']),
        ("Please make a selection.", ['prompt']),
        ("What would you like to do?", ['prompt', 'question']),
        ("How can I help you today?", ['prompt', 'question']),
        ("What can I do for you?", ['prompt', 'question']),
        ("Please speak now.", ['prompt']),
        ("Say something.", ['prompt']),
        ("I'm listening.", ['prompt']),
        ("Go ahead.", ['prompt']),
        ("Please wait.", ['prompt']),
        ("Please wait a moment.", ['prompt']),
        ("One moment please.", ['prompt']),
        ("Just a moment.", ['prompt']),
        ("Loading.", ['prompt']),
        ("Loading, please wait.", ['prompt']),
        ("Processing.", ['prompt']),
        ("Processing your request.", ['prompt']),
        ("Please stand by.", ['prompt']),
        ("Connecting.", ['prompt']),
        ("Searching.", ['prompt']),
        ("Calculating.", ['prompt']),
        ("Analyzing.", ['prompt']),
        ("Preparing.", ['prompt']),
        ("Getting ready.", ['prompt']),
        ("Almost there.", ['prompt']),
        ("Almost done.", ['prompt']),
        ("Just a few more seconds.", ['prompt']),
        ("This may take a moment.", ['prompt']),
        ("Saving.", ['prompt']),
        ("Saved.", ['prompt', 'confirmation']),
        ("Downloading.", ['prompt']),
        ("Uploading.", ['prompt']),
        ("Syncing.", ['prompt']),
        ("Updating.", ['prompt']),
        ("Installing.", ['prompt']),
        ("Configuring.", ['prompt']),
        ("Initializing.", ['prompt']),
        ("Restarting.", ['prompt']),
        ("Shutting down.", ['prompt']),
        ("Logging out.", ['prompt']),
        ("Signing out.", ['prompt']),
    ],

    # =========================================================================
    # COMMERCIALS & ADVERTISING
    # =========================================================================
    'commercial': [
        ("Buy now.", ['commercial']),
        ("Buy now!", ['commercial']),
        ("Order now.", ['commercial']),
        ("Order today.", ['commercial']),
        ("Call now.", ['commercial']),
        ("Act now.", ['commercial']),
        ("Shop now.", ['commercial']),
        ("Get yours today.", ['commercial']),
        ("Get yours now.", ['commercial']),
        ("Limited time offer.", ['commercial']),
        ("Limited time only.", ['commercial']),
        ("For a limited time.", ['commercial']),
        ("While supplies last.", ['commercial']),
        ("Don't miss out.", ['commercial']),
        ("Don't miss out!", ['commercial']),
        ("Don't wait.", ['commercial']),
        ("Hurry!", ['commercial']),
        ("Act fast.", ['commercial']),
        ("Special offer.", ['commercial']),
        ("Exclusive offer.", ['commercial']),
        ("Amazing deal.", ['commercial']),
        ("Great savings.", ['commercial']),
        ("Save big.", ['commercial']),
        ("Save now.", ['commercial']),
        ("Huge savings.", ['commercial']),
        ("Incredible value.", ['commercial']),
        ("Best price.", ['commercial']),
        ("Lowest price.", ['commercial']),
        ("Unbeatable price.", ['commercial']),
        ("Price match guarantee.", ['commercial']),
        ("Money back guarantee.", ['commercial']),
        ("Satisfaction guaranteed.", ['commercial']),
        ("Risk free.", ['commercial']),
        ("Free trial.", ['commercial']),
        ("Try it free.", ['commercial']),
        ("No obligation.", ['commercial']),
        ("No commitment.", ['commercial']),
        ("Free shipping.", ['commercial']),
        ("Free delivery.", ['commercial']),
        ("Free gift.", ['commercial']),
        ("Free gift with purchase.", ['commercial']),
        ("Call now and receive a free gift.", ['commercial']),
        ("Operators are standing by.", ['commercial']),
        ("Call toll free.", ['commercial']),
        ("Available for a limited time only.", ['commercial']),
        ("This offer won't last.", ['commercial']),
        ("Sale ends soon.", ['commercial']),
        ("Everything must go.", ['commercial']),
        ("Clearance sale.", ['commercial']),
        ("Going out of business.", ['commercial']),
        ("New and improved.", ['commercial']),
        ("Introducing.", ['commercial']),
        ("Now available.", ['commercial']),
        ("Finally available.", ['commercial']),
        ("As seen on TV.", ['commercial']),
        ("Try it today.", ['commercial']),
        ("You won't be disappointed.", ['commercial']),
        ("You'll love it.", ['commercial']),
        ("It's that simple.", ['commercial']),
        ("It's that easy.", ['commercial']),
        ("What are you waiting for?", ['commercial', 'question']),
    ],

    # =========================================================================
    # MOVIE TRAILER VOICE
    # =========================================================================
    'trailer_voice': [
        ("In a world.", ['trailer_voice', 'dramatic']),
        ("In a world where.", ['trailer_voice', 'dramatic']),
        ("This summer.", ['trailer_voice']),
        ("This fall.", ['trailer_voice']),
        ("This holiday season.", ['trailer_voice']),
        ("Coming soon.", ['trailer_voice']),
        ("Coming this summer.", ['trailer_voice']),
        ("Coming to theaters.", ['trailer_voice']),
        ("Now in theaters.", ['trailer_voice']),
        ("Now playing.", ['trailer_voice']),
        ("In theaters everywhere.", ['trailer_voice']),
        ("Now playing in theaters everywhere.", ['trailer_voice']),
        ("One man.", ['trailer_voice']),
        ("One woman.", ['trailer_voice']),
        ("One chance.", ['trailer_voice']),
        ("One destiny.", ['trailer_voice']),
        ("Everything changes.", ['trailer_voice']),
        ("Nothing will ever be the same.", ['trailer_voice']),
        ("The adventure begins.", ['trailer_voice']),
        ("The journey begins.", ['trailer_voice']),
        ("The legend begins.", ['trailer_voice']),
        ("The story of a lifetime.", ['trailer_voice']),
        ("An epic adventure.", ['trailer_voice']),
        ("A tale of.", ['trailer_voice']),
        ("Get ready.", ['trailer_voice']),
        ("Prepare yourself.", ['trailer_voice']),
        ("Brace yourself.", ['trailer_voice']),
        ("Are you ready?", ['trailer_voice', 'question']),
        ("Experience it.", ['trailer_voice']),
        ("Experience the.", ['trailer_voice']),
        ("Feel the.", ['trailer_voice']),
        ("Witness the.", ['trailer_voice']),
        ("Discover the.", ['trailer_voice']),
        ("From the director of.", ['trailer_voice']),
        ("From the creators of.", ['trailer_voice']),
        ("Based on a true story.", ['trailer_voice']),
        ("Based on the bestselling novel.", ['trailer_voice']),
        ("Critics are raving.", ['trailer_voice']),
        ("The must-see film of the year.", ['trailer_voice']),
        ("Rated PG-thirteen.", ['trailer_voice']),
        ("Rated PG.", ['trailer_voice']),
        ("Rated R.", ['trailer_voice']),
        ("Rated G.", ['trailer_voice']),
    ],

    # =========================================================================
    # PODCAST & RADIO
    # =========================================================================
    'podcast': [
        ("Hey everyone, welcome back to the show.", ['podcast', 'radio']),
        ("Welcome back to another episode.", ['podcast', 'radio']),
        ("Hello and welcome to the podcast.", ['podcast', 'radio']),
        ("Thanks for tuning in.", ['podcast', 'radio']),
        ("Thanks for listening.", ['podcast', 'radio']),
        ("Thank you for joining us.", ['podcast', 'radio']),
        ("Today we're going to talk about.", ['podcast', 'radio']),
        ("In today's episode.", ['podcast', 'radio']),
        ("On today's show.", ['podcast', 'radio']),
        ("Today's topic.", ['podcast', 'radio']),
        ("Let's get started.", ['podcast', 'radio']),
        ("Let's dive in.", ['podcast', 'radio']),
        ("Let's dive right in.", ['podcast', 'radio']),
        ("Let's get into it.", ['podcast', 'radio']),
        ("Before we get started.", ['podcast', 'radio']),
        ("Before we begin.", ['podcast', 'radio']),
        ("A quick word from our sponsors.", ['podcast', 'radio', 'commercial']),
        ("We'll be right back.", ['podcast', 'radio']),
        ("And we're back.", ['podcast', 'radio']),
        ("Welcome back.", ['podcast', 'radio']),
        ("That's all for today.", ['podcast', 'radio']),
        ("That's it for this episode.", ['podcast', 'radio']),
        ("Until next time.", ['podcast', 'radio', 'farewell']),
        ("See you next week.", ['podcast', 'radio', 'farewell']),
        ("Don't forget to subscribe.", ['podcast', 'radio']),
        ("Please subscribe.", ['podcast', 'radio']),
        ("Subscribe to the channel.", ['podcast', 'radio']),
        ("Hit that subscribe button.", ['podcast', 'radio']),
        ("Leave a review.", ['podcast', 'radio']),
        ("Leave a comment below.", ['podcast', 'radio']),
        ("Let us know what you think.", ['podcast', 'radio']),
        ("Send us your questions.", ['podcast', 'radio']),
        ("Email us at.", ['podcast', 'radio']),
        ("Follow us on social media.", ['podcast', 'radio']),
        ("Check out our website.", ['podcast', 'radio']),
        ("Links in the description.", ['podcast', 'radio']),
        ("Show notes are available.", ['podcast', 'radio']),
    ],

    'radio': [
        ("You're listening to.", ['radio']),
        ("This is.", ['radio']),
        ("That was.", ['radio']),
        ("Up next.", ['radio']),
        ("Coming up next.", ['radio']),
        ("Now playing.", ['radio']),
        ("Stay tuned.", ['radio']),
        ("Don't go anywhere.", ['radio']),
        ("We'll be right back.", ['radio']),
        ("After the break.", ['radio']),
        ("And we're back.", ['radio']),
        ("It's ten o'clock, here's the news.", ['radio', 'news']),
        ("Time for the weather.", ['radio', 'weather']),
        ("Traffic update.", ['radio', 'traffic']),
        ("Request line is open.", ['radio']),
        ("Call in now.", ['radio']),
        ("Caller, you're on the air.", ['radio']),
        ("Thanks for calling.", ['radio', 'thanks']),
        ("Shout out to.", ['radio']),
        ("Happy birthday to.", ['radio']),
        ("Congratulations to.", ['radio']),
        ("This one goes out to.", ['radio']),
        ("By request.", ['radio']),
        ("All the hits.", ['radio']),
        ("Non-stop music.", ['radio']),
        ("More music, less talk.", ['radio']),
        ("The best mix.", ['radio']),
    ],

    # =========================================================================
    # GAME VOICE
    # =========================================================================
    'game_voice': [
        ("Player one, ready.", ['game_voice']),
        ("Player two, ready.", ['game_voice']),
        ("Player three, ready.", ['game_voice']),
        ("Player four, ready.", ['game_voice']),
        ("All players ready.", ['game_voice']),
        ("Select your character.", ['game_voice', 'prompt']),
        ("Select your team.", ['game_voice', 'prompt']),
        ("Choose your fighter.", ['game_voice', 'prompt']),
        ("Choose your weapon.", ['game_voice', 'prompt']),
        ("Choose your difficulty.", ['game_voice', 'prompt']),
        ("Easy mode.", ['game_voice']),
        ("Normal mode.", ['game_voice']),
        ("Hard mode.", ['game_voice']),
        ("Expert mode.", ['game_voice']),
        ("Nightmare mode.", ['game_voice']),
        ("Get ready.", ['game_voice']),
        ("Get set.", ['game_voice']),
        ("Go!", ['game_voice']),
        ("Ready, set, go!", ['game_voice']),
        ("Three, two, one, fight!", ['game_voice']),
        ("Fight!", ['game_voice']),
        ("Round one.", ['game_voice']),
        ("Round two.", ['game_voice']),
        ("Round three.", ['game_voice']),
        ("Final round.", ['game_voice']),
        ("Bonus round.", ['game_voice']),
        ("Boss fight.", ['game_voice']),
        ("Game over.", ['game_voice']),
        ("Game over, man.", ['game_voice']),
        ("You win.", ['game_voice']),
        ("You win!", ['game_voice']),
        ("Winner!", ['game_voice']),
        ("Victory!", ['game_voice']),
        ("You lose.", ['game_voice']),
        ("You lose!", ['game_voice']),
        ("Loser.", ['game_voice']),
        ("Defeat.", ['game_voice']),
        ("Level complete.", ['game_voice']),
        ("Stage complete.", ['game_voice']),
        ("Stage clear.", ['game_voice']),
        ("Mission complete.", ['game_voice']),
        ("Mission accomplished.", ['game_voice']),
        ("Mission failed.", ['game_voice']),
        ("Objective complete.", ['game_voice']),
        ("Objective failed.", ['game_voice']),
        ("New objective.", ['game_voice']),
        ("New mission.", ['game_voice']),
        ("New high score.", ['game_voice']),
        ("High score.", ['game_voice']),
        ("New record.", ['game_voice']),
        ("Personal best.", ['game_voice']),
        ("K.O.", ['game_voice']),
        ("Knockout!", ['game_voice']),
        ("Fatality.", ['game_voice']),
        ("Flawless victory.", ['game_voice']),
        ("Perfect.", ['game_voice']),
        ("Perfect!", ['game_voice']),
        ("Excellent.", ['game_voice']),
        ("Excellent!", ['game_voice']),
        ("Awesome!", ['game_voice']),
        ("Amazing!", ['game_voice']),
        ("Incredible!", ['game_voice']),
        ("Unbelievable!", ['game_voice']),
        ("Combo.", ['game_voice']),
        ("Combo breaker.", ['game_voice']),
        ("Mega combo.", ['game_voice']),
        ("Ultra combo.", ['game_voice']),
        ("Double kill.", ['game_voice']),
        ("Triple kill.", ['game_voice']),
        ("Multi kill.", ['game_voice']),
        ("Monster kill.", ['game_voice']),
        ("Killing spree.", ['game_voice']),
        ("Rampage.", ['game_voice']),
        ("Unstoppable.", ['game_voice']),
        ("Dominating.", ['game_voice']),
        ("Godlike.", ['game_voice']),
        ("Legendary.", ['game_voice']),
        ("First blood.", ['game_voice']),
        ("Headshot.", ['game_voice']),
        ("Critical hit.", ['game_voice']),
        ("Super effective.", ['game_voice']),
        ("Not very effective.", ['game_voice']),
        ("It's super effective!", ['game_voice']),
        ("Level up.", ['game_voice']),
        ("Level up!", ['game_voice']),
        ("You leveled up.", ['game_voice']),
        ("Experience gained.", ['game_voice']),
        ("Skill unlocked.", ['game_voice']),
        ("Achievement unlocked.", ['game_voice']),
        ("Trophy earned.", ['game_voice']),
        ("New item.", ['game_voice']),
        ("Item acquired.", ['game_voice']),
        ("Item unlocked.", ['game_voice']),
        ("Weapon unlocked.", ['game_voice']),
        ("Power up.", ['game_voice']),
        ("Power up!", ['game_voice']),
        ("Bonus.", ['game_voice']),
        ("Extra life.", ['game_voice']),
        ("One up.", ['game_voice']),
        ("Health restored.", ['game_voice']),
        ("Shield activated.", ['game_voice']),
        ("Armor up.", ['game_voice']),
        ("Ammo full.", ['game_voice']),
        ("Reload.", ['game_voice']),
        ("Reloading.", ['game_voice']),
        ("Out of ammo.", ['game_voice']),
        ("Low health.", ['game_voice', 'alert']),
        ("Critical health.", ['game_voice', 'alert']),
        ("You died.", ['game_voice']),
        ("You are dead.", ['game_voice']),
        ("Respawning.", ['game_voice']),
        ("Respawning in three, two, one.", ['game_voice', 'counting']),
        ("Continue?", ['game_voice', 'question']),
        ("Insert coin.", ['game_voice']),
        ("Insert coin to continue.", ['game_voice']),
        ("Press start.", ['game_voice']),
        ("Press start to begin.", ['game_voice']),
        ("Press any button.", ['game_voice']),
        ("Paused.", ['game_voice']),
        ("Game paused.", ['game_voice']),
        ("Resume.", ['game_voice']),
        ("Resuming.", ['game_voice']),
        ("Checkpoint.", ['game_voice']),
        ("Checkpoint reached.", ['game_voice']),
        ("Save point.", ['game_voice']),
        ("Game saved.", ['game_voice']),
        ("Loading.", ['game_voice']),
        ("Now loading.", ['game_voice']),
        ("Waiting for players.", ['game_voice']),
        ("Match found.", ['game_voice']),
        ("Searching for match.", ['game_voice']),
        ("Connecting.", ['game_voice']),
        ("Connected.", ['game_voice']),
        ("Disconnected.", ['game_voice']),
        ("Connection lost.", ['game_voice', 'alert']),
        ("Host left.", ['game_voice']),
        ("You have been kicked.", ['game_voice']),
        ("You have been banned.", ['game_voice']),
        ("Team blue.", ['game_voice']),
        ("Team red.", ['game_voice']),
        ("Blue team wins.", ['game_voice']),
        ("Red team wins.", ['game_voice']),
        ("Capture the flag.", ['game_voice']),
        ("Flag captured.", ['game_voice']),
        ("Flag dropped.", ['game_voice']),
        ("Flag returned.", ['game_voice']),
        ("Base captured.", ['game_voice']),
        ("Objective secured.", ['game_voice']),
        ("Defend the objective.", ['game_voice']),
        ("Attack the objective.", ['game_voice']),
        ("Incoming.", ['game_voice', 'alert']),
        ("Enemy spotted.", ['game_voice', 'alert']),
        ("Hostile detected.", ['game_voice', 'alert']),
        ("Danger close.", ['game_voice', 'alert']),
        ("Air strike.", ['game_voice']),
        ("Artillery strike.", ['game_voice']),
        ("Nuke incoming.", ['game_voice', 'alert']),
        ("Tactical nuke incoming.", ['game_voice', 'alert']),
    ],

    # =========================================================================
    # FAMOUS QUOTES & CHARACTER LINES
    # =========================================================================
    'character': [
        ("I'll be back.", ['character']),
        ("May the force be with you.", ['character']),
        ("Here's looking at you, kid.", ['character']),
        ("You talking to me?", ['character']),
        ("Elementary, my dear Watson.", ['character']),
        ("To infinity and beyond!", ['character']),
        ("Houston, we have a problem.", ['character']),
        ("I am your father.", ['character']),
        ("I see dead people.", ['character']),
        ("You can't handle the truth!", ['character']),
        ("Life is like a box of chocolates.", ['character']),
        ("There's no place like home.", ['character']),
        ("I'm the king of the world!", ['character']),
        ("Why so serious?", ['character']),
        ("I'm going to make him an offer he can't refuse.", ['character']),
        ("You're gonna need a bigger boat.", ['character']),
        ("E.T. phone home.", ['character']),
        ("Here's Johnny!", ['character']),
        ("I feel the need, the need for speed.", ['character']),
        ("My precious.", ['character']),
        ("You shall not pass!", ['character']),
        ("Winter is coming.", ['character']),
        ("Live long and prosper.", ['character']),
        ("Beam me up, Scotty.", ['character']),
        ("Resistance is futile.", ['character']),
        ("I am inevitable.", ['character']),
        ("I am Iron Man.", ['character']),
        ("With great power comes great responsibility.", ['character']),
        ("It's a trap!", ['character']),
        ("Do or do not, there is no try.", ['character']),
    ],

    # =========================================================================
    # NEWS & JOURNALISM
    # =========================================================================
    'news': [
        ("Breaking news.", ['news']),
        ("Breaking news!", ['news']),
        ("This just in.", ['news']),
        ("We interrupt this program.", ['news']),
        ("Special report.", ['news']),
        ("Developing story.", ['news']),
        ("Live from.", ['news']),
        ("In today's headlines.", ['news']),
        ("Top stories.", ['news']),
        ("Our top story tonight.", ['news']),
        ("Headlines at the hour.", ['news']),
        ("Here's what's happening.", ['news']),
        ("In the news today.", ['news']),
        ("Latest developments.", ['news']),
        ("Sources say.", ['news']),
        ("According to reports.", ['news']),
        ("Officials confirm.", ['news']),
        ("Authorities report.", ['news']),
        ("Witnesses say.", ['news']),
        ("We now go live to our correspondent.", ['news']),
        ("Joining us now.", ['news']),
        ("For more on this story.", ['news']),
        ("Stay with us for updates.", ['news']),
        ("More details to come.", ['news']),
        ("We'll keep you updated.", ['news']),
        ("Back to you.", ['news']),
        ("That's all for now.", ['news']),
        ("Until next time.", ['news', 'farewell']),
        ("I'm reporting live.", ['news']),
        ("This has been a special report.", ['news']),
        ("That's the latest from here.", ['news']),
        ("Good evening.", ['news', 'greeting']),
        ("Good night.", ['news', 'farewell']),
    ],

    # =========================================================================
    # WEATHER
    # =========================================================================
    'weather': [
        ("Today's forecast.", ['weather']),
        ("The weather today.", ['weather']),
        ("Current conditions.", ['weather']),
        ("Looking at the forecast.", ['weather']),
        ("Here's your weather.", ['weather']),
        ("Sunny.", ['weather']),
        ("Sunny skies.", ['weather']),
        ("Mostly sunny.", ['weather']),
        ("Partly sunny.", ['weather']),
        ("Clear skies.", ['weather']),
        ("Sunny with clear skies.", ['weather']),
        ("Cloudy.", ['weather']),
        ("Partly cloudy.", ['weather']),
        ("Mostly cloudy.", ['weather']),
        ("Overcast.", ['weather']),
        ("Rainy.", ['weather']),
        ("Rain.", ['weather']),
        ("Light rain.", ['weather']),
        ("Heavy rain.", ['weather']),
        ("Showers.", ['weather']),
        ("Scattered showers.", ['weather']),
        ("Chance of rain.", ['weather']),
        ("Thunderstorms.", ['weather']),
        ("Thunderstorms expected.", ['weather']),
        ("Severe thunderstorms.", ['weather']),
        ("Lightning.", ['weather']),
        ("Hail.", ['weather']),
        ("Snow.", ['weather']),
        ("Light snow.", ['weather']),
        ("Heavy snow.", ['weather']),
        ("Snow showers.", ['weather']),
        ("Blizzard conditions.", ['weather']),
        ("Winter storm warning.", ['weather', 'alert']),
        ("Freezing rain.", ['weather']),
        ("Sleet.", ['weather']),
        ("Fog.", ['weather']),
        ("Dense fog advisory.", ['weather', 'alert']),
        ("Mist.", ['weather']),
        ("Hazy.", ['weather']),
        ("Windy.", ['weather']),
        ("Breezy.", ['weather']),
        ("Strong winds.", ['weather']),
        ("High winds.", ['weather']),
        ("Wind advisory.", ['weather', 'alert']),
        ("Humid.", ['weather']),
        ("Hot and humid.", ['weather']),
        ("Dry.", ['weather']),
        ("Hot.", ['weather']),
        ("Very hot.", ['weather']),
        ("Heat wave.", ['weather']),
        ("Heat advisory.", ['weather', 'alert']),
        ("Cold.", ['weather']),
        ("Very cold.", ['weather']),
        ("Freezing.", ['weather']),
        ("Below zero.", ['weather']),
        ("Wind chill advisory.", ['weather', 'alert']),
        ("High of seventy-five degrees.", ['weather', 'numbers']),
        ("Low of forty degrees.", ['weather', 'numbers']),
        ("Temperature: sixty-five degrees.", ['weather', 'numbers']),
        ("Current temperature.", ['weather']),
        ("It feels like.", ['weather']),
        ("Bundle up, it's going to be cold.", ['weather']),
        ("Dress warmly.", ['weather']),
        ("Don't forget your umbrella.", ['weather']),
        ("Perfect day to be outside.", ['weather']),
        ("Stay indoors if possible.", ['weather']),
        ("Conditions improving.", ['weather']),
        ("Conditions deteriorating.", ['weather']),
    ],

    # =========================================================================
    # SPORTS
    # =========================================================================
    'sports': [
        ("And the crowd goes wild!", ['sports']),
        ("What a play!", ['sports']),
        ("Incredible!", ['sports']),
        ("Unbelievable!", ['sports']),
        ("Did you see that?!", ['sports']),
        ("Goal!", ['sports']),
        ("Goooal!", ['sports']),
        ("He scores!", ['sports']),
        ("She scores!", ['sports']),
        ("Home run!", ['sports']),
        ("Out of the park!", ['sports']),
        ("It's a home run!", ['sports']),
        ("Grand slam!", ['sports']),
        ("Touchdown!", ['sports']),
        ("It's good!", ['sports']),
        ("Field goal is good!", ['sports']),
        ("Three pointer!", ['sports']),
        ("Nothing but net!", ['sports']),
        ("Slam dunk!", ['sports']),
        ("He shoots, he scores!", ['sports']),
        ("Strike!", ['sports']),
        ("Ball!", ['sports']),
        ("Foul ball!", ['sports']),
        ("Safe!", ['sports']),
        ("Out!", ['sports']),
        ("You're out!", ['sports']),
        ("Catch!", ['sports']),
        ("What a catch!", ['sports']),
        ("Interception!", ['sports']),
        ("Fumble!", ['sports']),
        ("First down!", ['sports']),
        ("And the winner is.", ['sports']),
        ("The champion!", ['sports']),
        ("Gold medal.", ['sports']),
        ("Silver medal.", ['sports']),
        ("Bronze medal.", ['sports']),
        ("World record!", ['sports']),
        ("New world record!", ['sports']),
        ("Personal best!", ['sports']),
        ("Photo finish!", ['sports']),
        ("Final score.", ['sports']),
        ("The final score is.", ['sports']),
        ("And the final score.", ['sports']),
        ("Time out.", ['sports']),
        ("Half time.", ['sports']),
        ("End of the first half.", ['sports']),
        ("End of the game.", ['sports']),
        ("That's the game!", ['sports']),
        ("Overtime!", ['sports']),
        ("Penalty!", ['sports']),
        ("Red card!", ['sports']),
        ("Yellow card!", ['sports']),
        ("Foul!", ['sports']),
        ("Technical foul!", ['sports']),
        ("Offside!", ['sports']),
        ("Corner kick.", ['sports']),
        ("Free kick.", ['sports']),
        ("Penalty kick.", ['sports']),
    ],

    # =========================================================================
    # TRAFFIC
    # =========================================================================
    'traffic': [
        ("Traffic report.", ['traffic']),
        ("Traffic update.", ['traffic']),
        ("Here's your traffic.", ['traffic']),
        ("On the roads.", ['traffic']),
        ("Smooth sailing.", ['traffic']),
        ("Traffic is light.", ['traffic']),
        ("Traffic is moderate.", ['traffic']),
        ("Traffic is heavy.", ['traffic']),
        ("Heavy traffic.", ['traffic']),
        ("Slow traffic.", ['traffic']),
        ("Stop and go traffic.", ['traffic']),
        ("Bumper to bumper.", ['traffic']),
        ("Heavy congestion.", ['traffic']),
        ("Heavy congestion on the highway.", ['traffic']),
        ("Traffic jam.", ['traffic']),
        ("Major delays.", ['traffic']),
        ("Minor delays.", ['traffic']),
        ("Expect delays.", ['traffic']),
        ("Allow extra time.", ['traffic']),
        ("Accident reported.", ['traffic', 'alert']),
        ("Accident reported ahead.", ['traffic', 'alert']),
        ("Accident cleared.", ['traffic']),
        ("Stalled vehicle.", ['traffic']),
        ("Disabled vehicle.", ['traffic']),
        ("Road closure.", ['traffic', 'alert']),
        ("Road closed.", ['traffic', 'alert']),
        ("Lane closure.", ['traffic']),
        ("Right lane closed.", ['traffic']),
        ("Left lane closed.", ['traffic']),
        ("All lanes open.", ['traffic']),
        ("Lanes reopened.", ['traffic']),
        ("Construction.", ['traffic']),
        ("Construction zone ahead.", ['traffic']),
        ("Roadwork ahead.", ['traffic']),
        ("Detour.", ['traffic']),
        ("Detour ahead.", ['traffic']),
        ("Take alternate route.", ['traffic']),
        ("Use alternate route.", ['traffic']),
        ("Clear conditions.", ['traffic']),
        ("No incidents.", ['traffic']),
        ("Drive safely.", ['traffic']),
    ],

    # =========================================================================
    # ALPHABET & PHONETIC
    # =========================================================================
    'alphabet': [
        ("A.", ['alphabet']),
        ("B.", ['alphabet']),
        ("C.", ['alphabet']),
        ("D.", ['alphabet']),
        ("E.", ['alphabet']),
        ("F.", ['alphabet']),
        ("G.", ['alphabet']),
        ("H.", ['alphabet']),
        ("I.", ['alphabet']),
        ("J.", ['alphabet']),
        ("K.", ['alphabet']),
        ("L.", ['alphabet']),
        ("M.", ['alphabet']),
        ("N.", ['alphabet']),
        ("O.", ['alphabet']),
        ("P.", ['alphabet']),
        ("Q.", ['alphabet']),
        ("R.", ['alphabet']),
        ("S.", ['alphabet']),
        ("T.", ['alphabet']),
        ("U.", ['alphabet']),
        ("V.", ['alphabet']),
        ("W.", ['alphabet']),
        ("X.", ['alphabet']),
        ("Y.", ['alphabet']),
        ("Z.", ['alphabet']),
    ],

    'phonetic': [
        ("Alpha.", ['phonetic', 'alphabet']),
        ("Bravo.", ['phonetic', 'alphabet']),
        ("Charlie.", ['phonetic', 'alphabet']),
        ("Delta.", ['phonetic', 'alphabet']),
        ("Echo.", ['phonetic', 'alphabet']),
        ("Foxtrot.", ['phonetic', 'alphabet']),
        ("Golf.", ['phonetic', 'alphabet']),
        ("Hotel.", ['phonetic', 'alphabet']),
        ("India.", ['phonetic', 'alphabet']),
        ("Juliet.", ['phonetic', 'alphabet']),
        ("Kilo.", ['phonetic', 'alphabet']),
        ("Lima.", ['phonetic', 'alphabet']),
        ("Mike.", ['phonetic', 'alphabet']),
        ("November.", ['phonetic', 'alphabet']),
        ("Oscar.", ['phonetic', 'alphabet']),
        ("Papa.", ['phonetic', 'alphabet']),
        ("Quebec.", ['phonetic', 'alphabet']),
        ("Romeo.", ['phonetic', 'alphabet']),
        ("Sierra.", ['phonetic', 'alphabet']),
        ("Tango.", ['phonetic', 'alphabet']),
        ("Uniform.", ['phonetic', 'alphabet']),
        ("Victor.", ['phonetic', 'alphabet']),
        ("Whiskey.", ['phonetic', 'alphabet']),
        ("X-ray.", ['phonetic', 'alphabet']),
        ("Yankee.", ['phonetic', 'alphabet']),
        ("Zulu.", ['phonetic', 'alphabet']),
    ],

    # =========================================================================
    # ANNOUNCEMENTS
    # =========================================================================
    'announcement': [
        ("Your attention please.", ['announcement']),
        ("Attention.", ['announcement']),
        ("Attention please.", ['announcement']),
        ("May I have your attention.", ['announcement']),
        ("May I have your attention please.", ['announcement']),
        ("This is an announcement.", ['announcement']),
        ("Announcement.", ['announcement']),
        ("Please stand by.", ['announcement']),
        ("Please wait.", ['announcement']),
        ("Please be patient.", ['announcement']),
        ("The meeting will begin shortly.", ['announcement']),
        ("The event will start soon.", ['announcement']),
        ("We are about to begin.", ['announcement']),
        ("Starting in five minutes.", ['announcement', 'time']),
        ("Last call.", ['announcement']),
        ("Final call.", ['announcement']),
        ("Final boarding call.", ['announcement']),
        ("All aboard.", ['announcement']),
        ("Now boarding.", ['announcement']),
        ("Now boarding at gate.", ['announcement']),
        ("Gate change.", ['announcement']),
        ("Please proceed to gate.", ['announcement']),
        ("Please proceed to gate seven.", ['announcement']),
        ("Flight delayed.", ['announcement']),
        ("Flight cancelled.", ['announcement']),
        ("Arriving at.", ['announcement']),
        ("Now arriving.", ['announcement']),
        ("Departing.", ['announcement']),
        ("Now departing.", ['announcement']),
        ("Next stop.", ['announcement']),
        ("This is your captain speaking.", ['announcement']),
        ("Ladies and gentlemen.", ['announcement']),
        ("Dear passengers.", ['announcement']),
        ("Welcome aboard.", ['announcement', 'greeting']),
        ("Thank you for flying with us.", ['announcement', 'thanks']),
        ("We hope you enjoyed your flight.", ['announcement']),
        ("We hope you had a pleasant journey.", ['announcement']),
        ("The store will be closing in fifteen minutes.", ['announcement', 'time']),
        ("The store is now closed.", ['announcement']),
        ("We are now open.", ['announcement']),
        ("Please visit us again.", ['announcement']),
        ("Thank you for your cooperation.", ['announcement', 'thanks']),
        ("Thank you for your patience.", ['announcement', 'thanks']),
        ("For your safety.", ['announcement']),
        ("Please remain seated.", ['announcement']),
        ("Please fasten your seatbelts.", ['announcement']),
        ("Emergency exits are located.", ['announcement']),
        ("In case of emergency.", ['announcement']),
        ("Please follow the instructions.", ['announcement']),
        ("Do not leave bags unattended.", ['announcement']),
        ("See something, say something.", ['announcement']),
        ("No smoking.", ['announcement']),
        ("No photography.", ['announcement']),
        ("No flash photography.", ['announcement']),
        ("Silence your phones.", ['announcement']),
        ("Please turn off your mobile phones.", ['announcement']),
        ("The show will begin shortly.", ['announcement']),
        ("Intermission.", ['announcement']),
        ("Please return to your seats.", ['announcement']),
        ("The show is about to resume.", ['announcement']),
        ("Thank you for attending.", ['announcement', 'thanks']),
        ("We hope you enjoyed the show.", ['announcement']),
    ],

    # =========================================================================
    # NARRATION
    # =========================================================================
    'narration': [
        ("Once upon a time.", ['narration']),
        ("Long ago.", ['narration']),
        ("In a distant land.", ['narration']),
        ("In the beginning.", ['narration']),
        ("And so the story begins.", ['narration']),
        ("Our story begins.", ['narration']),
        ("It all started.", ['narration']),
        ("Years ago.", ['narration']),
        ("Many years later.", ['narration']),
        ("Meanwhile.", ['narration']),
        ("Meanwhile, in another part of town.", ['narration']),
        ("At the same time.", ['narration']),
        ("Elsewhere.", ['narration']),
        ("Back at.", ['narration']),
        ("Little did they know.", ['narration']),
        ("What they didn't know was.", ['narration']),
        ("Unbeknownst to them.", ['narration']),
        ("As fate would have it.", ['narration']),
        ("And so it was.", ['narration']),
        ("And so it came to pass.", ['narration']),
        ("Time passed.", ['narration']),
        ("Days turned into weeks.", ['narration']),
        ("Weeks turned into months.", ['narration']),
        ("Months turned into years.", ['narration']),
        ("The journey continued.", ['narration']),
        ("Their adventure was just beginning.", ['narration']),
        ("But that's a story for another time.", ['narration']),
        ("To be continued.", ['narration']),
        ("And they lived happily ever after.", ['narration']),
        ("The end.", ['narration']),
        ("Chapter one.", ['narration']),
        ("Chapter two.", ['narration']),
        ("Chapter three.", ['narration']),
        ("Epilogue.", ['narration']),
        ("Prologue.", ['narration']),
    ],

    # =========================================================================
    # VOICEOVER
    # =========================================================================
    'voiceover': [
        ("In the beginning.", ['voiceover', 'narration']),
        ("As we can see here.", ['voiceover']),
        ("This diagram shows.", ['voiceover']),
        ("This image shows.", ['voiceover']),
        ("Let's take a closer look.", ['voiceover']),
        ("Looking at this more closely.", ['voiceover']),
        ("Notice how.", ['voiceover']),
        ("Pay attention to.", ['voiceover']),
        ("You'll notice that.", ['voiceover']),
        ("As you can see.", ['voiceover']),
        ("Here we see.", ['voiceover']),
        ("Here we have.", ['voiceover']),
        ("In this example.", ['voiceover']),
        ("For example.", ['voiceover']),
        ("For instance.", ['voiceover']),
        ("Consider this.", ['voiceover']),
        ("Think about it.", ['voiceover']),
        ("Imagine.", ['voiceover']),
        ("Picture this.", ['voiceover']),
        ("Let me explain.", ['voiceover']),
        ("Allow me to demonstrate.", ['voiceover']),
        ("I'll show you how.", ['voiceover']),
        ("Here's how it works.", ['voiceover', 'tutorial']),
        ("The process is simple.", ['voiceover']),
        ("It's quite straightforward.", ['voiceover']),
        ("In summary.", ['voiceover']),
        ("To summarize.", ['voiceover']),
        ("In conclusion.", ['voiceover']),
        ("To conclude.", ['voiceover']),
        ("And that's how it's done.", ['voiceover']),
        ("And there you have it.", ['voiceover']),
    ],

    # =========================================================================
    # SYSTEM & COMPUTER
    # =========================================================================
    'system': [
        ("System ready.", ['system', 'confirmation']),
        ("System online.", ['system', 'confirmation']),
        ("System offline.", ['system']),
        ("System error.", ['system', 'alert']),
        ("System failure.", ['system', 'alert']),
        ("System restored.", ['system', 'confirmation']),
        ("System rebooting.", ['system']),
        ("System restarting.", ['system']),
        ("System shutting down.", ['system']),
        ("Shutdown complete.", ['system']),
        ("Startup complete.", ['system', 'confirmation']),
        ("Boot sequence complete.", ['system', 'confirmation']),
        ("Initialization complete.", ['system', 'confirmation']),
        ("Loading complete.", ['system', 'confirmation']),
        ("Download complete.", ['system', 'confirmation']),
        ("Upload complete.", ['system', 'confirmation']),
        ("Installation complete.", ['system', 'confirmation']),
        ("Update complete.", ['system', 'confirmation']),
        ("Scan complete.", ['system', 'confirmation']),
        ("Backup complete.", ['system', 'confirmation']),
        ("Restore complete.", ['system', 'confirmation']),
        ("Sync complete.", ['system', 'confirmation']),
        ("Connection established.", ['system', 'confirmation']),
        ("Connected.", ['system', 'confirmation']),
        ("Disconnected.", ['system']),
        ("Connection failed.", ['system', 'alert']),
        ("Connection timeout.", ['system', 'alert']),
        ("Network error.", ['system', 'alert']),
        ("Server error.", ['system', 'alert']),
        ("Database error.", ['system', 'alert']),
        ("File not found.", ['system', 'alert']),
        ("Access denied.", ['system', 'alert']),
        ("Permission denied.", ['system', 'alert']),
        ("Authentication required.", ['system']),
        ("Authentication failed.", ['system', 'alert']),
        ("Authentication successful.", ['system', 'confirmation']),
        ("Login successful.", ['system', 'confirmation']),
        ("Login failed.", ['system', 'alert']),
        ("Logout successful.", ['system', 'confirmation']),
        ("Session expired.", ['system', 'alert']),
        ("Password incorrect.", ['system', 'alert']),
        ("Password changed.", ['system', 'confirmation']),
        ("Settings saved.", ['system', 'confirmation']),
        ("Changes saved.", ['system', 'confirmation']),
        ("File saved.", ['system', 'confirmation']),
        ("File deleted.", ['system', 'confirmation']),
        ("Message sent.", ['system', 'confirmation']),
        ("Email sent.", ['system', 'confirmation']),
        ("Operation complete.", ['system', 'confirmation']),
        ("Task complete.", ['system', 'confirmation']),
        ("Process complete.", ['system', 'confirmation']),
        ("Processing.", ['system']),
        ("Please wait.", ['system']),
        ("Loading.", ['system']),
        ("Searching.", ['system']),
        ("No results found.", ['system']),
        ("Search complete.", ['system', 'confirmation']),
        ("Copy complete.", ['system', 'confirmation']),
        ("Move complete.", ['system', 'confirmation']),
        ("Rename complete.", ['system', 'confirmation']),
        ("Format complete.", ['system', 'confirmation']),
        ("Virus detected.", ['system', 'alert']),
        ("Threat detected.", ['system', 'alert']),
        ("Malware detected.", ['system', 'alert']),
        ("Scan in progress.", ['system']),
        ("No threats found.", ['system', 'confirmation']),
        ("System is secure.", ['system', 'confirmation']),
        ("Firewall enabled.", ['system', 'confirmation']),
        ("Firewall disabled.", ['system']),
        ("Disk full.", ['system', 'alert']),
        ("Low disk space.", ['system', 'alert']),
        ("Memory full.", ['system', 'alert']),
        ("Low memory.", ['system', 'alert']),
        ("Battery low.", ['system', 'alert']),
        ("Battery critical.", ['system', 'alert']),
        ("Battery fully charged.", ['system', 'confirmation']),
        ("Charging.", ['system']),
        ("Power connected.", ['system']),
        ("Power disconnected.", ['system']),
        ("Airplane mode enabled.", ['system']),
        ("Airplane mode disabled.", ['system']),
        ("Do not disturb enabled.", ['system']),
        ("Do not disturb disabled.", ['system']),
        ("Silent mode enabled.", ['system']),
        ("Sound on.", ['system']),
        ("Muted.", ['system']),
        ("Unmuted.", ['system']),
        ("Microphone on.", ['system']),
        ("Microphone off.", ['system']),
        ("Camera on.", ['system']),
        ("Camera off.", ['system']),
        ("Recording.", ['system']),
        ("Recording stopped.", ['system']),
        ("Screenshot saved.", ['system', 'confirmation']),
        ("Clipboard copied.", ['system', 'confirmation']),
        ("Clipboard pasted.", ['system', 'confirmation']),
        ("Undo.", ['system']),
        ("Redo.", ['system']),
        ("Zoom in.", ['system']),
        ("Zoom out.", ['system']),
        ("Full screen.", ['system']),
        ("Exit full screen.", ['system']),
    ],

    # =========================================================================
    # AI ASSISTANT
    # =========================================================================
    'assistant': [
        ("Hello, how can I help you?", ['assistant', 'greeting']),
        ("Hi there, what can I do for you?", ['assistant', 'greeting']),
        ("How may I assist you today?", ['assistant', 'greeting']),
        ("What would you like me to do?", ['assistant', 'question']),
        ("I'm here to help.", ['assistant']),
        ("I'm listening.", ['assistant']),
        ("Go ahead, I'm listening.", ['assistant']),
        ("Sure, I can help with that.", ['assistant', 'confirmation']),
        ("Let me check that for you.", ['assistant']),
        ("Let me look that up.", ['assistant']),
        ("Give me a moment.", ['assistant']),
        ("One moment please.", ['assistant']),
        ("Working on it.", ['assistant']),
        ("Here's what I found.", ['assistant']),
        ("I found the following.", ['assistant']),
        ("Based on my search.", ['assistant']),
        ("According to my information.", ['assistant']),
        ("I'm sorry, I don't understand.", ['assistant', 'apology']),
        ("Could you please repeat that?", ['assistant', 'question']),
        ("I didn't quite catch that.", ['assistant']),
        ("Can you be more specific?", ['assistant', 'question']),
        ("I'm not sure what you mean.", ['assistant']),
        ("I don't have that information.", ['assistant']),
        ("I'm sorry, I can't do that.", ['assistant', 'apology', 'denial']),
        ("That's outside my capabilities.", ['assistant', 'denial']),
        ("Is there anything else?", ['assistant', 'question']),
        ("Is there anything else I can help with?", ['assistant', 'question']),
        ("Anything else?", ['assistant', 'question']),
        ("Do you have any other questions?", ['assistant', 'question']),
        ("Feel free to ask me anything.", ['assistant']),
        ("I'm always here to help.", ['assistant']),
        ("Happy to help.", ['assistant']),
        ("My pleasure.", ['assistant']),
        ("You're welcome.", ['assistant', 'thanks']),
        ("Goodbye!", ['assistant', 'farewell']),
        ("Have a great day!", ['assistant', 'farewell']),
        ("Take care!", ['assistant', 'farewell']),
        ("Until next time.", ['assistant', 'farewell']),
    ],

    # =========================================================================
    # EXCLAMATIONS & EMOTIONS
    # =========================================================================
    'exclamation': [
        ("Wow!", ['exclamation']),
        ("Amazing!", ['exclamation']),
        ("Incredible!", ['exclamation']),
        ("Fantastic!", ['exclamation']),
        ("Wonderful!", ['exclamation']),
        ("Excellent!", ['exclamation']),
        ("Brilliant!", ['exclamation']),
        ("Perfect!", ['exclamation']),
        ("Awesome!", ['exclamation']),
        ("Cool!", ['exclamation']),
        ("Great!", ['exclamation']),
        ("Nice!", ['exclamation']),
        ("Sweet!", ['exclamation']),
        ("Lovely!", ['exclamation']),
        ("Beautiful!", ['exclamation']),
        ("Gorgeous!", ['exclamation']),
        ("Stunning!", ['exclamation']),
        ("Spectacular!", ['exclamation']),
        ("Magnificent!", ['exclamation']),
        ("Marvelous!", ['exclamation']),
        ("Terrific!", ['exclamation']),
        ("Fabulous!", ['exclamation']),
        ("Superb!", ['exclamation']),
        ("Outstanding!", ['exclamation']),
        ("Exceptional!", ['exclamation']),
        ("Remarkable!", ['exclamation']),
        ("Impressive!", ['exclamation']),
        ("Bravo!", ['exclamation']),
        ("Well done!", ['exclamation']),
        ("Way to go!", ['exclamation']),
        ("Hooray!", ['exclamation']),
        ("Yay!", ['exclamation']),
        ("Woohoo!", ['exclamation']),
        ("Yes!", ['exclamation']),
        ("Hurrah!", ['exclamation']),
        ("Hallelujah!", ['exclamation']),
        ("Oh my!", ['exclamation']),
        ("Oh my goodness!", ['exclamation']),
        ("Oh wow!", ['exclamation']),
        ("Oh no!", ['exclamation']),
        ("Oops!", ['exclamation']),
        ("Whoops!", ['exclamation']),
        ("Uh oh!", ['exclamation']),
        ("Yikes!", ['exclamation']),
        ("Ouch!", ['exclamation']),
        ("Ow!", ['exclamation']),
        ("Phew!", ['exclamation']),
        ("Whew!", ['exclamation']),
        ("Ugh!", ['exclamation']),
        ("Argh!", ['exclamation']),
        ("Grr!", ['exclamation']),
        ("Hmm.", ['exclamation']),
        ("Hmm?", ['exclamation']),
        ("Huh?", ['exclamation']),
        ("Eh?", ['exclamation']),
        ("Whoa!", ['exclamation']),
        ("Ahh.", ['exclamation']),
        ("Ahhh!", ['exclamation']),
        ("Shh!", ['exclamation']),
        ("Hush!", ['exclamation']),
        ("Boo!", ['exclamation']),
        ("Surprise!", ['exclamation']),
        ("Ta-da!", ['exclamation']),
        ("Cheers!", ['exclamation']),
    ],
}

# =============================================================================
# GENERATION FUNCTIONS
# =============================================================================

def get_total_prompts():
    """Count total prompts across all categories."""
    return sum(len(prompts) for prompts in PROMPTS.values())

def generate_speech(text, voice_id, categories, voice_meta):
    """Generate a single speech sample and add to library."""
    try:
        # Build prompt with voice info for context
        tags = categories.copy()

        # Add voice-specific tags
        if voice_meta:
            if 'gender' in voice_meta:
                tags.append(voice_meta['gender'])
            if 'accent' in voice_meta:
                tags.append(voice_meta['accent'])

        response = requests.post(
            f"{BASE_URL}/api/tts/generate",
            json={
                "text": text,
                "voice": voice_id,
                "save_to_library": True,
                "tags": tags
            },
            timeout=120
        )

        if response.status_code == 200:
            return True, None
        else:
            return False, f"HTTP {response.status_code}: {response.text[:100]}"
    except requests.exceptions.Timeout:
        return False, "Timeout"
    except Exception as e:
        return False, str(e)

def main():
    parser = argparse.ArgumentParser(description='Generate comprehensive voice library')
    parser.add_argument('voice', nargs='?', default=DEFAULT_VOICE, help='Voice ID to use')
    parser.add_argument('--list-voices', action='store_true', help='List available voices')
    parser.add_argument('--dry-run', action='store_true', help='Show prompts without generating')
    parser.add_argument('--category', type=str, help='Only generate specific category')
    parser.add_argument('--start-from', type=int, default=0, help='Start from prompt number')
    args = parser.parse_args()

    if args.list_voices:
        print("Available voices:")
        for voice_id, meta in VOICE_METADATA.items():
            print(f"  {voice_id}: {meta}")
        return

    voice_id = args.voice
    voice_meta = VOICE_METADATA.get(voice_id, {})

    # Collect all prompts
    all_prompts = []
    for category, prompts in PROMPTS.items():
        if args.category and category != args.category:
            continue
        for text, tags in prompts:
            all_prompts.append((category, text, tags))

    total = len(all_prompts)

    print(f"Voice Library Generator")
    print("=" * 60)
    print(f"Voice: {voice_id}")
    print(f"Voice metadata: {voice_meta}")
    print(f"Total prompts: {total}")
    print()

    # Show category breakdown
    print("Categories:")
    for category, prompts in sorted(PROMPTS.items(), key=lambda x: -len(x[1])):
        if args.category and category != args.category:
            continue
        print(f"  - {category}: {len(prompts)}")
    print()

    if args.dry_run:
        print("Dry run - prompts that would be generated:")
        for i, (cat, text, tags) in enumerate(all_prompts[args.start_from:], args.start_from + 1):
            print(f"[{i}/{total}] {cat}: {text[:60]}... -> {tags}")
        return

    # Generate
    success_count = 0
    error_count = 0
    errors = []

    for i, (category, text, tags) in enumerate(all_prompts[args.start_from:], args.start_from + 1):
        display_text = text[:50] + "..." if len(text) > 50 else text
        print(f"[{i}/{total}] {category}: {display_text}", end=" ", flush=True)

        ok, error = generate_speech(text, voice_id, tags, voice_meta)

        if ok:
            print("OK")
            success_count += 1
        else:
            print(f"[ERR {error}]")
            error_count += 1
            errors.append((category, text, error))

        # Small delay to avoid overwhelming the server
        time.sleep(0.1)

        # Progress checkpoint every 50
        if i % 50 == 0:
            print(f"\n=== {success_count} generated, {error_count} failed ===\n")

    print()
    print("=" * 60)
    print(f"Complete! Success: {success_count}, Errors: {error_count}")

    if errors:
        print(f"\nFailed prompts:")
        for cat, text, err in errors[:20]:  # Show first 20 errors
            print(f"  - [{cat}] {text[:40]}...: {err}")
        if len(errors) > 20:
            print(f"  ... and {len(errors) - 20} more errors")

if __name__ == "__main__":
    main()
